SNS3
SatHandoverTest1 Class Reference
'Handover, test 1 test case implementation.
Public Member Functions
SatHandoverTest1 ()
virtual ~SatHandoverTest1 ()
Private Member Functions
virtual void DoRun (void)
std::vector< std::string > Split (std::string s, char del)
void TestFileValue (std::string path, uint32_t time, double expectedValue)
Detailed Description
'Handover, test 1 test case implementation.
This case tests that a application throughputs PerEntity are correct. It generates a conf with 2 GEO satellites, 2 GWs, 4 UTs (3 static and 1 moving) and 1 UT users per UT. Each UT user receives 40.96 kb/s.
Static UTs are connected to:
satellite 1, beam 36
satellite 1, beam 47
satellite 2, beam 46
Moving UT is:
At t = 8s, on satellite 1, beam 35
At t = 18s, on satellite 2, beam 20
Expected throughputs (after 8s):
40.96 kb/s per UT
122.88 kb/s on satellite 1, 40.96 kb/s on satellite 2
40.96 kb/s on beams 1/36, 1/47, 2/46 and 1/35
81.92 kb/s per GW
Expected throughputs (after 18s):
40.96 kb/s per UT
81.92 per satellite
40.96 kb/s on beams 1/36, 1/47, 2/46 and 2/20
40.96 kb/s on GW 1, 122.88 kb/s on GW 2
Definition at line 87 of file satellite-handover-test.cc.
Constructor & Destructor Documentation
SatHandoverTest1()
SatHandoverTest1::SatHandoverTest1 ()
Definition at line 101 of file satellite-handover-test.cc.
~SatHandoverTest1()
SatHandoverTest1::~SatHandoverTest1 () virtual
Definition at line 108 of file satellite-handover-test.cc.
Member Function Documentation
DoRun()
void SatHandoverTest1::DoRun (void) private virtual
Set regeneration mode
Set simulation output details
Enable packet trace
Definition at line 170 of file satellite-handover-test.cc.
References TestFileValue().
Split()
std::vector< std::string > SatHandoverTest1::Split (std::string s, char del) private
Definition at line 113 of file satellite-handover-test.cc.
Referenced by TestFileValue().
TestFileValue()
void SatHandoverTest1::TestFileValue (std::string path, uint32_t time, double expectedValue) private
Definition at line 127 of file satellite-handover-test.cc.
References Split().
Referenced by DoRun().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-handover-test.cc