SNS3
ns3::SatPhy Class Reference abstract
The SatPhy models the basic physical layer of the satellite system.
#include "satellite-phy.h"
Classes
struct CreateParam_t
Creation parameters for base PHY object.
Public Types
typedef Callback< void, uint32_t, uint32_t, uint32_t, uint8_t, double > AverageNormalizedOfferedLoadCallback
typedef Callback< SatChannelPair::ChannelPair_t, uint32_t, uint32_t > ChannelPairGetterCallback
Callback for retrieving a pair of SatChannel associated to a beam.
typedef Callback< void, uint32_t, uint32_t, Address, Address, double, bool > CnoCallback
typedef SatPhyRxCarrierConf::ErrorModel ErrorModel
Define ErrorModel in SatPhy.
typedef SatPhyRxCarrierConf::InterferenceEliminationModel InterferenceEliminationModel
Define InterferenceEliminationModel in SatPhy.
typedef SatPhyRxCarrierConf::InterferenceModel InterferenceModel
Define InterferenceModel in SatPhy.
typedef SatSignalParameters::PacketsInBurst_t PacketContainer_t
Define PacketContainer in SatPhy.
typedef Callback< void, PacketContainer_t, Ptr< SatSignalParameters > > ReceiveCallback
Public Member Functions
SatPhy (CreateParam_t &params)
Constructor to create PHY objects with parameters.
SatPhy (void)
Default constructor.
virtual ~SatPhy ()
Destructor.
void AverageNormalizedOfferedRandomAccessLoadInfo (uint32_t satId, uint32_t beamId, uint32_t carrierId, uint8_t allocationChannelId, double averageNormalizedOfferedLoad)
Function for getting the normalized offered load of the specific random access allocation channel.
void BeginEndScheduling ()
Begin frame/window end scheduling for processes utilizing frame length as interval.
double CalculateSinr (double sinr, double otherInterference)
Calculate final SINR with PHY specific parameters and given calculated SINR.
void CnoInfo (uint32_t satId, uint32_t beamId, Address source, Address destination, double cno, bool isSatelliteMac)
Function for getting the C/NO information.
void ConfigureRxCarriers (Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatSuperframeConf > superFrameConf)
Configure Rx carriers.
virtual void DoDispose (void)
Dispose of SatPhy.
virtual void DoInitialize (void)
Initialization of SatPhy.
virtual double GetAdditionalInterference ()=0
Get additional interference, used to compute final SINR at RX.
double GetDefaultFading () const
Get the default fading of the PHY.
TypeId GetInstanceTypeId (void) const
Derived from Object.
virtual Ptr< SatPhyRx > GetPhyRx () const
Get the SatPhyRx pointer.
virtual Ptr< SatPhyTx > GetPhyTx () const
Get the SatPhyTx pointer.
double GetRxAntennaGainDb () const
Get the maximum antenna gain of the receiver in dB.
double GetRxAntennaLossDb () const
Get the antenna loss of the receiver in dB.
double GetRxNoiseTemperatureDbk () const
Get the noise temperature of the receiver in dbK.
double GetTxAntennaGainDb () const
Get the maximum antenna gain of the transmitter in dB.
double GetTxAntennaLossDb () const
Get the antenna loss of the transmitter in dB.
Ptr< SatChannel > GetTxChannel ()
Get the Tx satellite channel.
double GetTxMaxPowerDbw () const
Get the maximum transmit power of the transmitter in dB.
double GetTxOboLossDb () const
Get the OBO loss of the transmitter in dB.
double GetTxOutputLossDb () const
Get the output loss of the transmitter in dB.
double GetTxPointingLossDb () const
Get the pointing loss of the transmitter in dB.
void Initialize ()
Initialize phy.
virtual void Receive (Ptr< SatSignalParameters > rxParams, bool phyError)
Receives packets from lower layer.
virtual void SendPdu (PacketContainer_t, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo)
Send Pdu to the PHY tx module (for initial transmissions from either UT or GW)
virtual void SendPduWithParams (Ptr< SatSignalParameters > rxParams)
Send Pdu to the PHY tx module (for satellite switch packet forwarding)
bool SetBeamId (uint32_t beamId)
Set the beamId this PHY is connected with.
void SetChannelPairGetterCallback (SatPhy::ChannelPairGetterCallback cb)
Set the channel pair getter callback.
void SetDefaultFading (double fading)
Set the default fading of the PHY.
void SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Set the node info class.
virtual void SetPhyRx (Ptr< SatPhyRx > phyRx)
Set the SatPhyRx module.
virtual void SetPhyTx (Ptr< SatPhyTx > phyTx)
Set the SatPhyTx module.
void SetRxAntennaGainDb (double gainDb)
Set the maximum antenna gain of the receiver in dB.
virtual void SetRxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility)
Set the receive antenna gain pattern.
void SetRxAntennaLossDb (double lossDb)
Set the antenna loss of the receiver in dB.
void SetRxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetRxNoiseTemperatureDbk (double temperatureDbk)
Set the noise temperature of the receiver in dbK.
void SetSatId (uint32_t satId)
Set the satId this PHY is connected with.
void SetTxAntennaGainDb (double gainDb)
Set the maximum antenna gain of the transmitter in dB.
virtual void SetTxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility)
Set the transmit antenna gain pattern.
void SetTxAntennaLossDb (double lossDb)
Set the antenna loss of the transmitter in dB.
void SetTxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetTxMaxPowerDbw (double powerDb)
Set the maximum transmit power of the transmitter in dB.
void SetTxOboLossDb (double lossDb)
Set the OBO loss of the transmitter in dB.
void SetTxOutputLossDb (double lossDb)
Set the output loss of the transmitter in dB.
void SetTxPointingLossDb (double lossDb)
Set the pointing loss of the transmitter in dB.
Static Public Member Functions
static TypeId GetTypeId (void)
Derived from Object.
Protected Member Functions
virtual SatEnums::SatLinkDir_t GetSatLinkRxDir ()
Get the link RX direction.
virtual SatEnums::SatLinkDir_t GetSatLinkTxDir ()
Get the link TX direction.
void ModcodTrace (Ptr< SatSignalParameters > rxParams)
Invoke the RxLinkModcod trace source for each received packet.
virtual void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
void SetTimeTag (SatPhy::PacketContainer_t packets)
Set SatPhyTimeTag of packets.
Protected Attributes
uint32_t m_beamId
Beam ID.
double m_eirpWoGainW
Calculated EIRP without gain in W.
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Time m_lastDelay
Last delay measurement.
Time m_lastLinkDelay
Last delay measurement for link.
Ptr< SatNodeInfo > m_nodeInfo
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
Trace callback used for packet tracing:
Ptr< SatPhyRx > m_phyRx
Pointer to internal SatPhyRx instance.
Ptr< SatPhyTx > m_phyTx
Pointer to internal SatPhyTx instance.
SatPhy::ChannelPairGetterCallback m_retrieveChannelPair
Callback for retrieving SatChannel pairs by beam.
SatPhy::ReceiveCallback m_rxCallback
The upper layer package receive callback.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
Traced callback for all received packets, including delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxJitterTrace
Traced callback for all received packets, including jitter information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkDelayTrace
Traced callback for all received packets, including link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkJitterTrace
Traced callback for all received packets, including link jitter information and the address of the senders.
TracedCallback< uint32_t, const Address & > m_rxLinkModcodTrace
Traced callback for all received packets, including link MODCOD information and the address of the senders.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced callback for all received packets, including the address of the senders.
uint32_t m_satId
Satellite ID.
Private Attributes
SatPhy::AverageNormalizedOfferedLoadCallback m_avgNormalizedOfferedLoadCallback
Average normalized offered load callback.
SatPhy::CnoCallback m_cnoCallback
The C/N0 info callback.
double m_defaultFadingValue
Default fading value.
double m_rxAntennaLossDb
Configured receiver antenna loss in Dbs.
double m_rxMaxAntennaGainDb
Configured maximum receiver antenna gain in dBi.
double m_rxNoiseTemperatureDbk
Configured receiver noise temperature in dBK.
double m_txAntennaLossDb
Configured transmitter antenna loss in Dbs.
double m_txMaxAntennaGainDb
Configured maximum transmitter antenna gain in dBi.
double m_txMaxPowerDbw
Configured maximum transmitter power in DbWs.
double m_txOboLossDb
Configured transmitter OBO loss in Dbs.
double m_txOutputLossDb
Configured transmitter output loss in Dbs.
double m_txPointingLossDb
Configured transmitter pointing loss in Dbs.
Detailed Description
The SatPhy models the basic physical layer of the satellite system.
SatPhy is the base class implementing the commonalities between different satellite nodes. This is a pure virtual class and actual implementations are located in:
SatUtPhy
SatGwPhy
SatOrbiterFeederPhy
SatOrbiterUserPhy
Definition at line 61 of file satellite-phy.h.
Member Typedef Documentation
AverageNormalizedOfferedLoadCallback
typedef Callback<void, uint32_t, uint32_t, uint32_t, uint8_t, double> ns3::SatPhy::AverageNormalizedOfferedLoadCallback
Parameters
satellite Id
beam Id
carrier Id
allocation channel Id
average normalized offered load
Definition at line 104 of file satellite-phy.h.
ChannelPairGetterCallback
typedef Callback<SatChannelPair::ChannelPair_t, uint32_t, uint32_t> ns3::SatPhy::ChannelPairGetterCallback
Callback for retrieving a pair of SatChannel associated to a beam.
Parameters
uint32_t beam ID
Returns
A pair of SatChannel to use as communication channel in this beam
Definition at line 503 of file satellite-phy.h.
CnoCallback
typedef Callback<void, uint32_t, uint32_t, Address, Address, double, bool> ns3::SatPhy::CnoCallback
Parameters
The id of the satellite.
The id of the beam.
The id (address) of the source or sender
The id (address) of the destination or receiver
C/N0 value
Definition at line 94 of file satellite-phy.h.
ErrorModel
typedef SatPhyRxCarrierConf::ErrorModel ns3::SatPhy::ErrorModel
Define ErrorModel in SatPhy.
Definition at line 75 of file satellite-phy.h.
InterferenceEliminationModel
typedef SatPhyRxCarrierConf::InterferenceEliminationModel ns3::SatPhy::InterferenceEliminationModel
Define InterferenceEliminationModel in SatPhy.
Definition at line 71 of file satellite-phy.h.
InterferenceModel
typedef SatPhyRxCarrierConf::InterferenceModel ns3::SatPhy::InterferenceModel
Define InterferenceModel in SatPhy.
Definition at line 67 of file satellite-phy.h.
PacketContainer_t
typedef SatSignalParameters::PacketsInBurst_t ns3::SatPhy::PacketContainer_t
Define PacketContainer in SatPhy.
Definition at line 79 of file satellite-phy.h.
ReceiveCallback
typedef Callback<void, PacketContainer_t, Ptr<SatSignalParameters> > ns3::SatPhy::ReceiveCallback
Parameters
the container of pointers to packets received
the id of the beam where packet is from
Definition at line 85 of file satellite-phy.h.
Constructor & Destructor Documentation
SatPhy() [1/2]
ns3::SatPhy::SatPhy (void)
Default constructor.
Definition at line 52 of file satellite-phy.cc.
SatPhy() [2/2]
ns3::SatPhy::SatPhy (CreateParam_t & params)
Constructor to create PHY objects with parameters.
Definition at line 74 of file satellite-phy.cc.
References ns3::SatEnums::DVB_GW, ns3::SatEnums::DVB_ORBITER, ns3::SatEnums::DVB_UT, ns3::SatEnums::LORA_GW, ns3::SatEnums::LORA_ORBITER, ns3::SatEnums::LORA_UT, ns3::SatPhy::CreateParam_t::m_beamId, m_beamId, ns3::SatPhy::CreateParam_t::m_device, m_phyRx, m_phyTx, ns3::SatPhy::CreateParam_t::m_rxCh, ns3::SatPhy::CreateParam_t::m_satId, m_satId, ns3::SatPhy::CreateParam_t::m_standard, and ns3::SatPhy::CreateParam_t::m_txCh.
~SatPhy()
ns3::SatPhy::~SatPhy () virtual
Destructor.
Definition at line 246 of file satellite-phy.cc.
Member Function Documentation
AverageNormalizedOfferedRandomAccessLoadInfo()
void ns3::SatPhy::AverageNormalizedOfferedRandomAccessLoadInfo (uint32_t satId, uint32_t beamId, uint32_t carrierId, uint8_t allocationChannelId, double averageNormalizedOfferedLoad)
Function for getting the normalized offered load of the specific random access allocation channel.
Parameters
satId Satellite id of average normalized load is received
beamId Beam id of average normalized load is received
carrierId Carrier id of average normalized load is received
allocationChannelId allocation channel ID
averageNormalizedOfferedLoad Value of average normalized offered load
Definition at line 645 of file satellite-phy.cc.
References m_avgNormalizedOfferedLoadCallback.
Referenced by Initialize().
BeginEndScheduling()
void ns3::SatPhy::BeginEndScheduling (void)
Begin frame/window end scheduling for processes utilizing frame length as interval.
Definition at line 332 of file satellite-phy.cc.
References m_phyRx.
CalculateSinr()
double ns3::SatPhy::CalculateSinr (double sinr, double otherInterference)
Calculate final SINR with PHY specific parameters and given calculated SINR.
Additional interference value is added.
Parameters
sinr Calculated SINR
otherInterference Interference to add to the sinr
Returns
Final SINR
Definition at line 264 of file satellite-phy.cc.
CnoInfo()
void ns3::SatPhy::CnoInfo (uint32_t satId, uint32_t beamId, Address source, Address destination, double cno, bool isSatelliteMac)
Function for getting the C/NO information.
Parameters
beamId Beam id of C/N0 is received
source Id (address) of the source (sender)
destination Id (address) of the destination
cno Value of the C/N0
isSatelliteMac If true, cno corresponds to link SAT to GW; if false, cno corresponds to link UT to GW
Definition at line 633 of file satellite-phy.cc.
References m_cnoCallback.
Referenced by Initialize().
ConfigureRxCarriers()
void ns3::SatPhy::ConfigureRxCarriers (Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatSuperframeConf > superFrameConf)
Configure Rx carriers.
Parameters
carrierConf Carrier configuration class
superFrameConf Superframe configuration
Definition at line 300 of file satellite-phy.cc.
References m_phyRx.
Referenced by ns3::SatGwPhy::SatGwPhy(), ns3::SatOrbiterFeederPhy::SatOrbiterFeederPhy(), ns3::SatOrbiterUserPhy::SatOrbiterUserPhy(), and ns3::SatUtPhy::SatUtPhy().
DoDispose()
void ns3::SatPhy::DoDispose (void) virtual
Dispose of SatPhy.
Reimplemented in ns3::SatUtPhy, ns3::SatOrbiterUserPhy, ns3::SatOrbiterFeederPhy, and ns3::SatGwPhy.
Definition at line 252 of file satellite-phy.cc.
References m_phyRx, and m_phyTx.
Referenced by ns3::SatGwPhy::DoDispose().
DoInitialize()
void ns3::SatPhy::DoInitialize (void) virtual
Initialization of SatPhy.
Reimplemented in ns3::SatUtPhy, ns3::SatOrbiterUserPhy, ns3::SatOrbiterFeederPhy, and ns3::SatGwPhy.
Definition at line 201 of file satellite-phy.cc.
Referenced by ns3::SatGwPhy::DoInitialize().
GetAdditionalInterference()
virtual double ns3::SatPhy::GetAdditionalInterference () pure virtual
Get additional interference, used to compute final SINR at RX.
Returns
Additional interference
Implemented in ns3::SatUtPhy, ns3::SatOrbiterUserPhy, ns3::SatOrbiterFeederPhy, and ns3::SatGwPhy.
GetDefaultFading()
double ns3::SatPhy::GetDefaultFading () const inline
Get the default fading of the PHY.
Returns
the default fading of the PHY.
Definition at line 340 of file satellite-phy.h.
References m_defaultFadingValue.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetInstanceTypeId()
TypeId ns3::SatPhy::GetInstanceTypeId (void) const
Derived from Object.
Definition at line 194 of file satellite-phy.cc.
References GetTypeId().
GetPhyRx()
Ptr< SatPhyRx > ns3::SatPhy::GetPhyRx () const virtual
Get the SatPhyRx pointer.
Returns
a pointer to the SatPhyRx instance
Definition at line 346 of file satellite-phy.cc.
References m_phyRx.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetPhyTx()
Ptr< SatPhyTx > ns3::SatPhy::GetPhyTx (void) const virtual
Get the SatPhyTx pointer.
Returns
a pointer to the SatPhyTx instance
Definition at line 339 of file satellite-phy.cc.
References m_phyTx.
Referenced by ns3::SatOrbiterFeederPhy::SatOrbiterFeederPhy(), ns3::SatOrbiterUserPhy::SatOrbiterUserPhy(), ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetRxAntennaGainDb()
double ns3::SatPhy::GetRxAntennaGainDb () const inline
Get the maximum antenna gain of the receiver in dB.
Returns
the receiver noise temperature in dB.
Definition at line 196 of file satellite-phy.h.
References m_rxMaxAntennaGainDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetRxAntennaLossDb()
double ns3::SatPhy::GetRxAntennaLossDb () const inline
Get the antenna loss of the receiver in dB.
Returns
the receiver antenna loss in dB.
Definition at line 214 of file satellite-phy.h.
References m_rxAntennaLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetRxNoiseTemperatureDbk()
double ns3::SatPhy::GetRxNoiseTemperatureDbk () const inline
Get the noise temperature of the receiver in dbK.
Returns
the receiver noise temperature in dbK.
Definition at line 178 of file satellite-phy.h.
References m_rxNoiseTemperatureDbk.
Referenced by ns3::SatGwPhy::SatGwPhy(), ns3::SatOrbiterFeederPhy::SatOrbiterFeederPhy(), ns3::SatOrbiterUserPhy::SatOrbiterUserPhy(), ns3::SatUtPhy::SatUtPhy(), ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetSatLinkRxDir()
SatEnums::SatLinkDir_t ns3::SatPhy::GetSatLinkRxDir () protected virtual
Get the link RX direction.
Must be implemented by child clases.
Returns
The link RX direction
Reimplemented in ns3::SatUtPhy, ns3::SatOrbiterUserPhy, ns3::SatOrbiterFeederPhy, and ns3::SatGwPhy.
Definition at line 480 of file satellite-phy.cc.
References ns3::SatEnums::LD_UNDEFINED.
Referenced by ModcodTrace(), and Receive().
GetSatLinkTxDir()
SatEnums::SatLinkDir_t ns3::SatPhy::GetSatLinkTxDir () protected virtual
Get the link TX direction.
Must be implemented by child clases.
Returns
The link TX direction
Reimplemented in ns3::SatUtPhy, ns3::SatOrbiterUserPhy, ns3::SatOrbiterFeederPhy, and ns3::SatGwPhy.
Definition at line 474 of file satellite-phy.cc.
References ns3::SatEnums::LD_UNDEFINED.
Referenced by SendPdu().
GetTxAntennaGainDb()
double ns3::SatPhy::GetTxAntennaGainDb () const inline
Get the maximum antenna gain of the transmitter in dB.
Returns
the transmitter noise temperature in dB.
Definition at line 232 of file satellite-phy.h.
References m_txMaxAntennaGainDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetTxAntennaLossDb()
double ns3::SatPhy::GetTxAntennaLossDb () const inline
Get the antenna loss of the transmitter in dB.
Returns
the transmitter antenna loss in dB.
Definition at line 322 of file satellite-phy.h.
References m_txAntennaLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetTxChannel()
Ptr< SatChannel > ns3::SatPhy::GetTxChannel ()
Get the Tx satellite channel.
Returns
the Tx channel
Definition at line 367 of file satellite-phy.cc.
References m_phyTx.
GetTxMaxPowerDbw()
double ns3::SatPhy::GetTxMaxPowerDbw () const inline
Get the maximum transmit power of the transmitter in dB.
Returns
the transmitter transmit power in dB.
Definition at line 250 of file satellite-phy.h.
References m_txMaxPowerDbw.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetTxOboLossDb()
double ns3::SatPhy::GetTxOboLossDb () const inline
Get the OBO loss of the transmitter in dB.
Returns
the transmitter OBO loss in dB.
Definition at line 304 of file satellite-phy.h.
References m_txOboLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetTxOutputLossDb()
double ns3::SatPhy::GetTxOutputLossDb () const inline
Get the output loss of the transmitter in dB.
Returns
the transmitter output loss in dB.
Definition at line 268 of file satellite-phy.h.
References m_txOutputLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetTxPointingLossDb()
double ns3::SatPhy::GetTxPointingLossDb () const inline
Get the pointing loss of the transmitter in dB.
Returns
the transmitter pointing loss in dB.
Definition at line 286 of file satellite-phy.h.
References m_txPointingLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
GetTypeId()
TypeId ns3::SatPhy::GetTypeId (void) static
Derived from Object.
Definition at line 136 of file satellite-phy.cc.
References m_avgNormalizedOfferedLoadCallback, m_cnoCallback, m_isStatisticsTagsEnabled, m_packetTrace, m_rxCallback, m_rxDelayTrace, m_rxJitterTrace, m_rxLinkDelayTrace, m_rxLinkJitterTrace, m_rxLinkModcodTrace, and m_rxTrace.
Referenced by GetInstanceTypeId().
Initialize()
void ns3::SatPhy::Initialize ()
Initialize phy.
Definition at line 208 of file satellite-phy.cc.
References AverageNormalizedOfferedRandomAccessLoadInfo(), CnoInfo(), ns3::SatUtils::DbWToW(), m_avgNormalizedOfferedLoadCallback, m_beamId, m_cnoCallback, m_defaultFadingValue, m_eirpWoGainW, m_phyRx, m_phyTx, m_rxAntennaLossDb, m_rxMaxAntennaGainDb, m_satId, m_txAntennaLossDb, m_txMaxAntennaGainDb, m_txMaxPowerDbw, m_txOboLossDb, m_txOutputLossDb, m_txPointingLossDb, and Receive().
ModcodTrace()
void ns3::SatPhy::ModcodTrace (Ptr< SatSignalParameters > rxParams) protected
Invoke the RxLinkModcod trace source for each received packet.
Parameters
rxParams Pointer to SatSignalParameters of packets received.
Definition at line 550 of file satellite-phy.cc.
References ns3::SatAddressE2ETag::GetE2EDestAddress(), ns3::SatAddressE2ETag::GetE2ESourceAddress(), GetSatLinkRxDir(), ns3::SatEnums::LD_FORWARD, ns3::SatEnums::LD_RETURN, m_isStatisticsTagsEnabled, and m_rxLinkModcodTrace.
Referenced by ns3::SatOrbiterFeederPhy::Receive(), ns3::SatOrbiterUserPhy::Receive(), and Receive().
Receive()
void ns3::SatPhy::Receive (Ptr< SatSignalParameters > rxParams, bool phyError) virtual
Receives packets from lower layer.
Parameters
rxParams Packet reception parameters
phyError Boolean indicating whether the packet successfully received or not?
Reimplemented in ns3::SatUtPhy, ns3::SatOrbiterUserPhy, and ns3::SatOrbiterFeederPhy.
Definition at line 595 of file satellite-phy.cc.
References ns3::SatUtils::GetPacketInfo(), GetSatLinkRxDir(), ns3::SatEnums::LL_PHY, m_nodeInfo, m_packetTrace, m_rxCallback, ModcodTrace(), ns3::SatEnums::PACKET_DROP, ns3::SatEnums::PACKET_RECV, and RxTraces().
Referenced by Initialize(), and ns3::SatUtPhy::Receive().
RxTraces()
void ns3::SatPhy::RxTraces (SatPhy::PacketContainer_t packets) protected virtual
Invoke the Rx trace source for each received packet.
Parameters
packets Container of the pointers to the packets received.
Reimplemented in ns3::SatOrbiterUserPhy, and ns3::SatOrbiterFeederPhy.
Definition at line 486 of file satellite-phy.cc.
References ns3::SatPhyLinkTimeTag::GetSenderLinkTimestamp(), ns3::SatPhyTimeTag::GetSenderTimestamp(), ns3::SatAddressTag::GetSourceAddress(), ns3::SatAddressTag::GetTypeId(), m_isStatisticsTagsEnabled, m_lastDelay, m_lastLinkDelay, m_rxDelayTrace, m_rxJitterTrace, m_rxLinkDelayTrace, m_rxLinkJitterTrace, and m_rxTrace.
Referenced by Receive().
SendPdu()
void ns3::SatPhy::SendPdu (PacketContainer_t p, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo) virtual
Send Pdu to the PHY tx module (for initial transmissions from either UT or GW)
Parameters
p packet to be sent
carrierId Carrier id for the packet transmission
duration the packet transmission duration (from MAC layer)
txInfo Tx information (e.g. packet type, modcod, waveform ID)
Definition at line 376 of file satellite-phy.cc.
References ns3::SatSignalParameters::txInfo_s::crdsaUniquePacketId, ns3::SatSignalParameters::txInfo_s::fecBlockSizeInBytes, ns3::SatSignalParameters::txInfo_s::frameType, ns3::SatUtils::GetPacketInfo(), GetSatLinkTxDir(), ns3::SatEnums::LL_PHY, m_beamId, m_eirpWoGainW, m_nodeInfo, m_packetTrace, m_phyTx, m_satId, ns3::SatSignalParameters::txInfo_s::modCod, ns3::SatEnums::PACKET_SENT, ns3::SatSignalParameters::txInfo_s::packetType, SetTimeTag(), ns3::SatSignalParameters::txInfo_s::sliceId, and ns3::SatSignalParameters::txInfo_s::waveformId.
Referenced by ns3::SatGwHelperDvb::Install(), and ns3::SatUtHelperDvb::Install().
SendPduWithParams()
void ns3::SatPhy::SendPduWithParams (Ptr< SatSignalParameters > rxParams) virtual
Send Pdu to the PHY tx module (for satellite switch packet forwarding)
Parameters
rxParams Transmission parameters
This method is not meant to be used in this class. It is overriden in the inherited classes.
Reimplemented in ns3::SatOrbiterUserPhy, and ns3::SatOrbiterFeederPhy.
Definition at line 420 of file satellite-phy.cc.
SetBeamId()
bool ns3::SatPhy::SetBeamId (uint32_t beamId)
Set the beamId this PHY is connected with.
Parameters
beamId Satellite beam id
Definition at line 441 of file satellite-phy.cc.
References m_beamId, m_phyRx, and m_phyTx.
Referenced by ns3::SatGwPhy::PerformHandover(), and ns3::SatUtPhy::PerformHandover().
SetChannelPairGetterCallback()
void ns3::SatPhy::SetChannelPairGetterCallback (SatPhy::ChannelPairGetterCallback cb)
Set the channel pair getter callback.
Parameters
cb callback to invoke whenever a SatChannel pair for a beam is required.
Definition at line 661 of file satellite-phy.cc.
References m_retrieveChannelPair.
SetDefaultFading()
void ns3::SatPhy::SetDefaultFading (double fading) inline
Set the default fading of the PHY.
Parameters
fading the default fading of the PHY.
Definition at line 349 of file satellite-phy.h.
References m_defaultFadingValue.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetNodeInfo()
void ns3::SatPhy::SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Set the node info class.
Parameters
nodeInfo Node information related to this SatPhy
Definition at line 324 of file satellite-phy.cc.
References m_nodeInfo, and m_phyRx.
SetPhyRx()
void ns3::SatPhy::SetPhyRx (Ptr< SatPhyRx > phyRx) virtual
Set the SatPhyRx module.
Parameters
phyRx Receiver PHY module
Definition at line 360 of file satellite-phy.cc.
References m_phyRx.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetPhyTx()
void ns3::SatPhy::SetPhyTx (Ptr< SatPhyTx > phyTx) virtual
Set the SatPhyTx module.
Parameters
phyTx Transmitter PHY module
Definition at line 353 of file satellite-phy.cc.
References m_phyTx.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetRxAntennaGainDb()
void ns3::SatPhy::SetRxAntennaGainDb (double gainDb) inline
Set the maximum antenna gain of the receiver in dB.
Parameters
gainDb the receiver antenna gain in dB.
Definition at line 205 of file satellite-phy.h.
References m_rxMaxAntennaGainDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetRxAntennaGainPattern()
void ns3::SatPhy::SetRxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility) virtual
Set the receive antenna gain pattern.
Parameters
agp antenna gain pattern
mobility mobility model of satellite
Definition at line 292 of file satellite-phy.cc.
References m_phyRx.
SetRxAntennaLossDb()
void ns3::SatPhy::SetRxAntennaLossDb (double lossDb) inline
Set the antenna loss of the receiver in dB.
Parameters
lossDb the receiver antenna loss in dB.
Definition at line 223 of file satellite-phy.h.
References m_rxAntennaLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetRxFadingContainer()
void ns3::SatPhy::SetRxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
Parameters
fadingContainer fading container
Definition at line 308 of file satellite-phy.cc.
References m_phyRx.
SetRxNoiseTemperatureDbk()
void ns3::SatPhy::SetRxNoiseTemperatureDbk (double temperatureDbk) inline
Set the noise temperature of the receiver in dbK.
Parameters
temperatureDbk the receiver noise temperature in dbK.
Definition at line 187 of file satellite-phy.h.
References m_rxNoiseTemperatureDbk.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetSatId()
void ns3::SatPhy::SetSatId (uint32_t satId)
Set the satId this PHY is connected with.
Parameters
satId Satellite ID
Definition at line 432 of file satellite-phy.cc.
References m_phyRx, m_phyTx, and m_satId.
Referenced by ns3::SatGwPhy::PerformHandover(), and ns3::SatUtPhy::PerformHandover().
SetTimeTag()
void ns3::SatPhy::SetTimeTag (SatPhy::PacketContainer_t packets) protected
Set SatPhyTimeTag of packets.
Parameters
packets Container of the pointers to the packets to tag.
Definition at line 456 of file satellite-phy.cc.
References m_isStatisticsTagsEnabled.
Referenced by SendPdu(), ns3::SatOrbiterFeederPhy::SendPduWithParams(), and ns3::SatOrbiterUserPhy::SendPduWithParams().
SetTxAntennaGainDb()
void ns3::SatPhy::SetTxAntennaGainDb (double gainDb) inline
Set the maximum antenna gain of the transmitter in dB.
Parameters
gainDb the transmitter antenna gain in dB.
Definition at line 241 of file satellite-phy.h.
References m_txMaxAntennaGainDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetTxAntennaGainPattern()
void ns3::SatPhy::SetTxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility) virtual
Set the transmit antenna gain pattern.
Parameters
agp antenna gain pattern
mobility mobility model of satellite
Definition at line 284 of file satellite-phy.cc.
References m_phyTx.
SetTxAntennaLossDb()
void ns3::SatPhy::SetTxAntennaLossDb (double lossDb) inline
Set the antenna loss of the transmitter in dB.
Parameters
lossDb the transmitter antenna loss in dB.
Definition at line 331 of file satellite-phy.h.
References m_txAntennaLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetTxFadingContainer()
void ns3::SatPhy::SetTxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
Parameters
fadingContainer fading container
Definition at line 316 of file satellite-phy.cc.
References m_phyTx.
SetTxMaxPowerDbw()
void ns3::SatPhy::SetTxMaxPowerDbw (double powerDb) inline
Set the maximum transmit power of the transmitter in dB.
Parameters
powerDb the transmitter transmit power in dB.
Definition at line 259 of file satellite-phy.h.
References m_txMaxPowerDbw.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetTxOboLossDb()
void ns3::SatPhy::SetTxOboLossDb (double lossDb) inline
Set the OBO loss of the transmitter in dB.
Parameters
lossDb the transmitter OBO loss in dB.
Definition at line 313 of file satellite-phy.h.
References m_txOboLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetTxOutputLossDb()
void ns3::SatPhy::SetTxOutputLossDb (double lossDb) inline
Set the output loss of the transmitter in dB.
Parameters
lossDb the transmitter output loss in dB.
Definition at line 277 of file satellite-phy.h.
References m_txOutputLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
SetTxPointingLossDb()
void ns3::SatPhy::SetTxPointingLossDb (double lossDb) inline
Set the pointing loss of the transmitter in dB.
Parameters
lossDb the transmitter pointing loss in dB.
Definition at line 295 of file satellite-phy.h.
References m_txPointingLossDb.
Referenced by ns3::SatGwPhy::GetTypeId(), ns3::SatOrbiterFeederPhy::GetTypeId(), ns3::SatOrbiterUserPhy::GetTypeId(), and ns3::SatUtPhy::GetTypeId().
Member Data Documentation
m_avgNormalizedOfferedLoadCallback
SatPhy::AverageNormalizedOfferedLoadCallback ns3::SatPhy::m_avgNormalizedOfferedLoadCallback private
Average normalized offered load callback.
Definition at line 656 of file satellite-phy.h.
Referenced by AverageNormalizedOfferedRandomAccessLoadInfo(), GetTypeId(), and Initialize().
m_beamId
uint32_t ns3::SatPhy::m_beamId protected
Beam ID.
Definition at line 625 of file satellite-phy.h.
Referenced by SatPhy(), ns3::SatGwPhy::AssignNewSatChannels(), ns3::SatUtPhy::AssignNewSatChannels(), Initialize(), ns3::SatGwPhy::PerformHandover(), ns3::SatUtPhy::PerformHandover(), SendPdu(), and SetBeamId().
m_cnoCallback
SatPhy::CnoCallback ns3::SatPhy::m_cnoCallback private
The C/N0 info callback.
Definition at line 651 of file satellite-phy.h.
Referenced by CnoInfo(), GetTypeId(), and Initialize().
m_defaultFadingValue
double ns3::SatPhy::m_defaultFadingValue private
Default fading value.
Definition at line 706 of file satellite-phy.h.
Referenced by GetDefaultFading(), Initialize(), and SetDefaultFading().
m_eirpWoGainW
double ns3::SatPhy::m_eirpWoGainW protected
Calculated EIRP without gain in W.
Definition at line 630 of file satellite-phy.h.
Referenced by Initialize(), SendPdu(), ns3::SatOrbiterFeederPhy::SendPduWithParams(), and ns3::SatOrbiterUserPhy::SendPduWithParams().
m_isStatisticsTagsEnabled
bool ns3::SatPhy::m_isStatisticsTagsEnabled protected
EnableStatisticsTags attribute.
Definition at line 635 of file satellite-phy.h.
Referenced by GetTypeId(), ModcodTrace(), ns3::SatOrbiterFeederPhy::RxTraces(), ns3::SatOrbiterUserPhy::RxTraces(), RxTraces(), and SetTimeTag().
m_lastDelay
Time ns3::SatPhy::m_lastDelay protected
Last delay measurement.
Used to compute jitter.
Definition at line 640 of file satellite-phy.h.
Referenced by RxTraces().
m_lastLinkDelay
Time ns3::SatPhy::m_lastLinkDelay protected
Last delay measurement for link.
Used to compute link jitter.
Definition at line 645 of file satellite-phy.h.
Referenced by ns3::SatOrbiterFeederPhy::RxTraces(), ns3::SatOrbiterUserPhy::RxTraces(), and RxTraces().
m_nodeInfo
Ptr<SatNodeInfo> ns3::SatPhy::m_nodeInfo protected
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
Definition at line 605 of file satellite-phy.h.
Referenced by ns3::SatOrbiterFeederPhy::Receive(), ns3::SatOrbiterUserPhy::Receive(), Receive(), ns3::SatOrbiterFeederPhy::SendFromQueue(), ns3::SatOrbiterUserPhy::SendFromQueue(), SendPdu(), ns3::SatOrbiterFeederPhy::SendPduWithParams(), ns3::SatOrbiterUserPhy::SendPduWithParams(), and SetNodeInfo().
m_packetTrace
TracedCallback<Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string> ns3::SatPhy::m_packetTrace protected
Trace callback used for packet tracing:
Definition at line 563 of file satellite-phy.h.
Referenced by GetTypeId(), ns3::SatOrbiterFeederPhy::Receive(), ns3::SatOrbiterUserPhy::Receive(), Receive(), ns3::SatOrbiterFeederPhy::SendFromQueue(), ns3::SatOrbiterUserPhy::SendFromQueue(), SendPdu(), ns3::SatOrbiterFeederPhy::SendPduWithParams(), and ns3::SatOrbiterUserPhy::SendPduWithParams().
m_phyRx
Ptr<SatPhyRx> ns3::SatPhy::m_phyRx protected
Pointer to internal SatPhyRx instance.
Definition at line 615 of file satellite-phy.h.
Referenced by SatPhy(), ns3::SatGwPhy::AssignNewSatChannels(), ns3::SatUtPhy::AssignNewSatChannels(), BeginEndScheduling(), ConfigureRxCarriers(), DoDispose(), GetPhyRx(), Initialize(), ns3::SatGwPhy::PerformHandover(), ns3::SatUtPhy::PerformHandover(), SetBeamId(), SetNodeInfo(), SetPhyRx(), SetRxAntennaGainPattern(), SetRxFadingContainer(), and SetSatId().
m_phyTx
Ptr<SatPhyTx> ns3::SatPhy::m_phyTx protected
Pointer to internal SatPhyTx instance.
Definition at line 610 of file satellite-phy.h.
Referenced by SatPhy(), ns3::SatGwPhy::AssignNewSatChannels(), ns3::SatUtPhy::AssignNewSatChannels(), DoDispose(), GetPhyTx(), GetTxChannel(), Initialize(), ns3::SatUtPhy::IsTxPossible(), ns3::SatGwPhy::PerformHandover(), ns3::SatUtPhy::PerformHandover(), ns3::SatOrbiterFeederPhy::SendFromQueue(), ns3::SatOrbiterUserPhy::SendFromQueue(), SendPdu(), ns3::SatOrbiterFeederPhy::SendPduWithParams(), ns3::SatOrbiterUserPhy::SendPduWithParams(), SetBeamId(), SetPhyTx(), SetSatId(), SetTxAntennaGainPattern(), and SetTxFadingContainer().
m_retrieveChannelPair
SatPhy::ChannelPairGetterCallback ns3::SatPhy::m_retrieveChannelPair protected
Callback for retrieving SatChannel pairs by beam.
Definition at line 550 of file satellite-phy.h.
Referenced by ns3::SatGwPhy::AssignNewSatChannels(), ns3::SatUtPhy::AssignNewSatChannels(), ns3::SatGwPhy::PerformHandover(), ns3::SatUtPhy::PerformHandover(), and SetChannelPairGetterCallback().
m_rxAntennaLossDb
double ns3::SatPhy::m_rxAntennaLossDb private
Configured receiver antenna loss in Dbs.
Definition at line 671 of file satellite-phy.h.
Referenced by GetRxAntennaLossDb(), Initialize(), and SetRxAntennaLossDb().
m_rxCallback
SatPhy::ReceiveCallback ns3::SatPhy::m_rxCallback protected
The upper layer package receive callback.
Definition at line 545 of file satellite-phy.h.
Referenced by GetTypeId(), ns3::SatOrbiterFeederPhy::Receive(), ns3::SatOrbiterUserPhy::Receive(), and Receive().
m_rxDelayTrace
TracedCallback<const Time&, const Address&> ns3::SatPhy::m_rxDelayTrace protected
Traced callback for all received packets, including delay information and the address of the senders.
Definition at line 575 of file satellite-phy.h.
Referenced by GetTypeId(), and RxTraces().
m_rxJitterTrace
TracedCallback<const Time&, const Address&> ns3::SatPhy::m_rxJitterTrace protected
Traced callback for all received packets, including jitter information and the address of the senders.
Definition at line 587 of file satellite-phy.h.
Referenced by GetTypeId(), and RxTraces().
m_rxLinkDelayTrace
TracedCallback<const Time&, const Address&> ns3::SatPhy::m_rxLinkDelayTrace protected
Traced callback for all received packets, including link delay information and the address of the senders.
Definition at line 581 of file satellite-phy.h.
Referenced by GetTypeId(), ns3::SatOrbiterFeederPhy::RxTraces(), ns3::SatOrbiterUserPhy::RxTraces(), and RxTraces().
m_rxLinkJitterTrace
TracedCallback<const Time&, const Address&> ns3::SatPhy::m_rxLinkJitterTrace protected
Traced callback for all received packets, including link jitter information and the address of the senders.
Definition at line 593 of file satellite-phy.h.
Referenced by GetTypeId(), ns3::SatOrbiterFeederPhy::RxTraces(), ns3::SatOrbiterUserPhy::RxTraces(), and RxTraces().
m_rxLinkModcodTrace
TracedCallback<uint32_t, const Address&> ns3::SatPhy::m_rxLinkModcodTrace protected
Traced callback for all received packets, including link MODCOD information and the address of the senders.
Definition at line 599 of file satellite-phy.h.
Referenced by GetTypeId(), and ModcodTrace().
m_rxMaxAntennaGainDb
double ns3::SatPhy::m_rxMaxAntennaGainDb private
Configured maximum receiver antenna gain in dBi.
Definition at line 666 of file satellite-phy.h.
Referenced by GetRxAntennaGainDb(), Initialize(), and SetRxAntennaGainDb().
m_rxNoiseTemperatureDbk
double ns3::SatPhy::m_rxNoiseTemperatureDbk private
Configured receiver noise temperature in dBK.
Definition at line 661 of file satellite-phy.h.
Referenced by GetRxNoiseTemperatureDbk(), and SetRxNoiseTemperatureDbk().
m_rxTrace
TracedCallback<Ptr<const Packet>, const Address&> ns3::SatPhy::m_rxTrace protected
Traced callback for all received packets, including the address of the senders.
Definition at line 569 of file satellite-phy.h.
Referenced by GetTypeId(), ns3::SatOrbiterFeederPhy::RxTraces(), ns3::SatOrbiterUserPhy::RxTraces(), and RxTraces().
m_satId
uint32_t ns3::SatPhy::m_satId protected
Satellite ID.
Definition at line 620 of file satellite-phy.h.
Referenced by SatPhy(), ns3::SatGwPhy::AssignNewSatChannels(), ns3::SatUtPhy::AssignNewSatChannels(), Initialize(), ns3::SatGwPhy::PerformHandover(), ns3::SatUtPhy::PerformHandover(), SendPdu(), and SetSatId().
m_txAntennaLossDb
double ns3::SatPhy::m_txAntennaLossDb private
Configured transmitter antenna loss in Dbs.
Definition at line 701 of file satellite-phy.h.
Referenced by GetTxAntennaLossDb(), Initialize(), and SetTxAntennaLossDb().
m_txMaxAntennaGainDb
double ns3::SatPhy::m_txMaxAntennaGainDb private
Configured maximum transmitter antenna gain in dBi.
Definition at line 676 of file satellite-phy.h.
Referenced by GetTxAntennaGainDb(), Initialize(), and SetTxAntennaGainDb().
m_txMaxPowerDbw
double ns3::SatPhy::m_txMaxPowerDbw private
Configured maximum transmitter power in DbWs.
Definition at line 681 of file satellite-phy.h.
Referenced by GetTxMaxPowerDbw(), Initialize(), and SetTxMaxPowerDbw().
m_txOboLossDb
double ns3::SatPhy::m_txOboLossDb private
Configured transmitter OBO loss in Dbs.
Definition at line 696 of file satellite-phy.h.
Referenced by GetTxOboLossDb(), Initialize(), and SetTxOboLossDb().
m_txOutputLossDb
double ns3::SatPhy::m_txOutputLossDb private
Configured transmitter output loss in Dbs.
Definition at line 686 of file satellite-phy.h.
Referenced by GetTxOutputLossDb(), Initialize(), and SetTxOutputLossDb().
m_txPointingLossDb
double ns3::SatPhy::m_txPointingLossDb private
Configured transmitter pointing loss in Dbs.
Definition at line 691 of file satellite-phy.h.
Referenced by GetTxPointingLossDb(), Initialize(), and SetTxPointingLossDb().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-phy.h
/builds/sns3/satellite/satellite/model/satellite-phy.cc