SNS3
ns3::SatUtHelperDvb Class Reference
Creates needed objects for DVB UT nodes like SatOrbiterNetDevice objects.
#include "satellite-ut-helper-dvb.h"
Public Member Functions
SatUtHelperDvb ()
Default constructor.
SatUtHelperDvb (SatTypedefs::CarrierBandwidthConverter_t carrierBandwidthConverter, uint32_t rtnLinkCarrierCount, Ptr< SatSuperframeSeq > seq, SatMac::ReadCtrlMsgCallback readCb, SatMac::ReserveCtrlMsgCallback reserveCb, SatMac::SendCtrlMsgCallback sendCb, RandomAccessSettings_s randomAccessSettings)
Create a SatUtHelperDvb to make life easier when creating Satellite point to point network connections.
virtual ~SatUtHelperDvb ()
Destructor.
TypeId GetInstanceTypeId (void) const
Derived from Object.
virtual Ptr< NetDevice > Install (Ptr< Node > n, uint32_t satId, uint32_t beamId, Ptr< SatChannel > fCh, Ptr< SatChannel > rCh, Ptr< SatNetDevice > gwNd, Ptr< SatNcc > ncc, Address satUserAddress, SatPhy::ChannelPairGetterCallback cbChannel, SatMac::RoutingUpdateCallback cbRouting)
Public Member Functions inherited from ns3::SatUtHelper
SatUtHelper ()
Default constructor.
SatUtHelper (SatTypedefs::CarrierBandwidthConverter_t carrierBandwidthConverter, uint32_t rtnLinkCarrierCount, Ptr< SatSuperframeSeq > seq, SatMac::ReadCtrlMsgCallback readCb, SatMac::ReserveCtrlMsgCallback reserveCb, SatMac::SendCtrlMsgCallback sendCb, RandomAccessSettings_s randomAccessSettings)
Create a SatUtHelper to make life easier when creating Satellite point to point network connections.
virtual ~SatUtHelper ()
Destructor.
void EnableCreationTraces (Ptr< OutputStreamWrapper > stream, CallbackBase &cb)
Enables creation traces to be written in given file.
TypeId GetInstanceTypeId (void) const
Derived from Object.
void Initialize (Ptr< SatLinkResultsFwd > lrFwd)
NetDeviceContainer Install (NodeContainer c, uint32_t satId, uint32_t beamId, Ptr< SatChannel > fCh, Ptr< SatChannel > rCh, Ptr< SatNetDevice > gwNd, Ptr< SatNcc > ncc, Address satUserAddress, SatPhy::ChannelPairGetterCallback cbChannel, SatMac::RoutingUpdateCallback cbRouting)
void SetChannelAttribute (std::string name, const AttributeValue &value)
Set an attribute value to be propagated to each Channel created by the helper.
void SetDeviceAttribute (std::string name, const AttributeValue &value)
Set an attribute value to be propagated to each NetDevice created by the helper.
void SetPhyAttribute (std::string name, const AttributeValue &value)
Set an attribute value to be propagated to each Phy created by the helper.
Static Public Member Functions
static TypeId GetTypeId (void)
Derived from Object.
Static Public Member Functions inherited from ns3::SatUtHelper
static TypeId GetTypeId (void)
Derived from Object.
Additional Inherited Members
Protected Attributes inherited from ns3::SatUtHelper
bool m_asyncAccess
SatTypedefs::CarrierBandwidthConverter_t m_carrierBandwidthConverter
ObjectFactory m_channelFactory
bool m_crdsaOnlyForControl
Planned CRDSA usage:
TracedCallback< std::string > m_creationTrace
Trace callback for creation traces.
double m_daConstantErrorRate
SatPhy::InterferenceModel m_daInterferenceModel
ObjectFactory m_deviceFactory
bool m_enableChannelEstimationError
Enable channel estimation error modeling at forward link receiver (= UT).
SatPhy::ErrorModel m_errorModel
uint32_t m_fwdLinkCarrierCount
Ptr< SatLinkResults > m_linkResults
Ptr< SatLowerLayerServiceConf > m_llsConf
Configured lower layer service configuration.
RandomAccessSettings_s m_raSettings
The used random access model settings.
SatMac::ReadCtrlMsgCallback m_readCtrlCb
SatMac::ReserveCtrlMsgCallback m_reserveCtrlCb
SatMac::SendCtrlMsgCallback m_sendCtrlCb
Ptr< SatSuperframeSeq > m_superframeSeq
Detailed Description
Creates needed objects for DVB UT nodes like SatOrbiterNetDevice objects.
Handles needed configuration for the UT nodes.
Definition at line 43 of file satellite-ut-helper-dvb.h.
Constructor & Destructor Documentation
SatUtHelperDvb() [1/2]
ns3::SatUtHelperDvb::SatUtHelperDvb ()
Default constructor.
Definition at line 80 of file satellite-ut-helper-dvb.cc.
SatUtHelperDvb() [2/2]
ns3::SatUtHelperDvb::SatUtHelperDvb (SatTypedefs::CarrierBandwidthConverter_t carrierBandwidthConverter, uint32_t rtnLinkCarrierCount, Ptr< SatSuperframeSeq > seq, SatMac::ReadCtrlMsgCallback readCb, SatMac::ReserveCtrlMsgCallback reserveCb, SatMac::SendCtrlMsgCallback sendCb, RandomAccessSettings_s randomAccessSettings)
Create a SatUtHelperDvb to make life easier when creating Satellite point to point network connections.
Definition at line 88 of file satellite-ut-helper-dvb.cc.
~SatUtHelperDvb()
virtual ns3::SatUtHelperDvb::~SatUtHelperDvb () inline virtual
Destructor.
Definition at line 76 of file satellite-ut-helper-dvb.h.
Member Function Documentation
GetInstanceTypeId()
TypeId ns3::SatUtHelperDvb::GetInstanceTypeId (void) const
Derived from Object.
Definition at line 73 of file satellite-ut-helper-dvb.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatUtHelperDvb::GetTypeId (void) static
Derived from Object.
Definition at line 65 of file satellite-ut-helper-dvb.cc.
Referenced by GetInstanceTypeId().
Install()
Ptr< NetDevice > ns3::SatUtHelperDvb::Install (Ptr< Node > n, uint32_t satId, uint32_t beamId, Ptr< SatChannel > fCh, Ptr< SatChannel > rCh, Ptr< SatNetDevice > gwNd, Ptr< SatNcc > ncc, Address satUserAddress, SatPhy::ChannelPairGetterCallback cbChannel, SatMac::RoutingUpdateCallback cbRouting) virtual
Parameters
n node
satId id of the satellite
beamId id of the beam
fCh forward channel
rCh return channel
gwNd satellite netdevice of the GW
ncc NCC (Network Control Center)
satUserAddress MAC address of satellite user link
Returns
Net device installed to node
This method creates a ns3::SatChannel with the attributes configured by SatUtHelper::SetChannelAttribute, then, for each node in the input container, we create a ns3::SatNetDevice with the requested attributes, a queue for this ns3::NetDevice, and associate the resulting ns3::NetDevice with the ns3::Node and ns3::SatChannel.
Channel estimation errors
create RA module with defaults
attach callbacks
attach the RA module
Implements ns3::SatUtHelper.
Definition at line 107 of file satellite-ut-helper-dvb.cc.
References ns3::SatRequestManager::AssignedDaResources(), ns3::SatLlc::BuffersEmpty(), ns3::SatRequestManager::CnoUpdated(), ns3::SatEnums::CONTROL_FID, ns3::SatLlc::ControlBuffersEmpty(), ns3::SatUtMac::ControlMsgTransmissionPossible(), ns3::SatEnums::DVB_UT, ns3::SatNcc::GetBeamScheduler(), ns3::SatQueue::GetQueueStatistics(), ns3::SatLlc::GetSchedulingContexts(), ns3::SatMobilityObserver::GetTimingAdvance(), ns3::SatUtPhy::IsTxPossible(), ns3::SatUtMac::LogonMsgTransmissionPossible(), ns3::SatPhy::CreateParam_t::m_beamId, ns3::SatUtHelper::m_carrierBandwidthConverter, ns3::SatUtHelper::m_crdsaOnlyForControl, ns3::SatUtHelper::m_daConstantErrorRate, ns3::SatUtHelper::m_daInterferenceModel, ns3::SatPhy::CreateParam_t::m_device, ns3::SatUtHelper::m_deviceFactory, ns3::SatUtHelper::m_enableChannelEstimationError, ns3::SatUtHelper::m_errorModel, ns3::SatUtHelper::m_fwdLinkCarrierCount, ns3::SatUtHelper::m_linkResults, ns3::SatUtHelper::m_llsConf, ns3::SatUtHelper::RandomAccessSettings_s::m_raCollisionModel, ns3::SatUtHelper::RandomAccessSettings_s::m_raInterferenceEliminationModel, ns3::SatUtHelper::RandomAccessSettings_s::m_raInterferenceModel, ns3::SatUtHelper::RandomAccessSettings_s::m_randomAccessModel, ns3::SatUtHelper::m_raSettings, ns3::SatUtHelper::m_readCtrlCb, ns3::SatUtHelper::m_reserveCtrlCb, ns3::SatPhy::CreateParam_t::m_rxCh, ns3::SatPhy::CreateParam_t::m_satId, ns3::SatUtHelper::m_sendCtrlCb, ns3::SatPhy::CreateParam_t::m_standard, ns3::SatUtHelper::m_superframeSeq, ns3::SatPhy::CreateParam_t::m_txCh, ns3::SatUtLlc::NotifyTxOpportunity(), ns3::SatEnums::NT_UT, ns3::SatUtPhy::PerformHandover(), ns3::SatEnums::RA_MODEL_ESSA, ns3::SatEnums::RA_MODEL_OFF, ns3::SatNetDevice::Receive(), ns3::SatLlc::Receive(), ns3::SatUtMac::Receive(), ns3::SatRequestManager::ReceiveQueueEvent(), ns3::SatUtMac::ReceiveQueueEvent(), ns3::SatUtMac::ReceiveQueueEventEssa(), ns3::SatEnums::REGENERATION_NETWORK, ns3::SatEnums::REGENERATION_PHY, ns3::SatNetDevice::SendControlMsg(), ns3::SatRequestManager::SendHandoverRecommendation(), ns3::SatUtMac::SendLogon(), ns3::SatRequestManager::SendLogonMessage(), ns3::SatPhy::SendPdu(), ns3::SatRequestManager::SetGwAddress(), ns3::SatUtLlc::SetGwAddress(), ns3::SatHandoverModule::SetHandoverRequestCallback(), ns3::SatUtMac::SetRaChannel(), ns3::SatAddressE2ETag::SIZE, ns3::SatConstVariables::SUPERFRAME_SEQUENCE, ns3::SatEnums::TRANSPARENT, and ns3::SatUtPhy::UpdateSliceSubscription().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-ut-helper-dvb.h
/builds/sns3/satellite/satellite/helper/satellite-ut-helper-dvb.cc