SNS3
ns3::SatOrbiterMac Class Reference abstract
The SatOrbiterMac models the global link MAC layer of the satellite node.
#include "satellite-orbiter-mac.h"
Public Types
typedef Callback< Ptr< SatBeamScheduler >, uint32_t, uint32_t > BeamSchedulerCallback
Callback to get the SatBeamScheduler from the beam ID for handover.
typedef Callback< void, SatPhy::PacketContainer_t, Ptr< SatSignalParameters > > ReceiveNetDeviceCallback
typedef Callback< void, Ptr< SatSignalParameters > > TransmitCallback
Public Types inherited from ns3::SatMac
typedef Callback< Ptr< SatBeamScheduler >, uint32_t, uint32_t > BeamSchedulerCallback
Callback to get the SatBeamScheduler from the beam ID for handover.
typedef Callback< void, Ptr< const Packet > > LoraReceiveCallback
Callback to receive packet by upper layer.
typedef Callback< Ptr< SatControlMessage >, uint32_t > ReadCtrlMsgCallback
Callback to read control messages from container storing control messages.
typedef Callback< void, Ptr< Packet >, Mac48Address, Mac48Address > ReceiveCallback
Callback to receive packet by upper layer.
typedef Callback< uint32_t, Ptr< SatControlMessage > > ReserveCtrlMsgCallback
Callback to reserve an id and initially store the control message.
typedef Callback< void, Address, Address > RoutingUpdateCallback
Callback to update routing and ARP tables after handover.
typedef Callback< uint32_t, uint32_t > SendCtrlMsgCallback
Callback to send a control message and allocate a recv ID for it.
typedef Callback< void, SatPhy::PacketContainer_t, uint32_t, Time, SatSignalParameters::txInfo_s > TransmitCallback
Callback to send packet to lower layer.
typedef Callback< void > UpdateIslCallback
Callback to update ISL routes when handovers are performed.
Public Member Functions
SatOrbiterMac (uint32_t satId, uint32_t beamId)
Construct a SatOrbiterMac.
SatOrbiterMac (void)
Default constructor.
virtual ~SatOrbiterMac ()
Destructor for SatOrbiterMac.
virtual bool AddPeer (Mac48Address address)=0
Add a remote peer to this MAC.
virtual void DoDispose (void)
Dispose of this class instance.
virtual void DoInitialize (void)
virtual void EnquePacket (Ptr< Packet > packet)=0
Add new packet to the LLC queue.
virtual Time GetGuardTime () const
TypeId GetInstanceTypeId (void) const
virtual bool RemovePeer (Mac48Address address)=0
Remove a remote peer from this MAC.
void SetBeamSchedulerCallback (SatOrbiterMac::BeamSchedulerCallback cb)
Set the beam scheduler callback.
void SetFwdScheduler (Ptr< SatFwdLinkScheduler > fwdScheduler)
Method to set link scheduler (forward or SCPC)
virtual void SetGuardTime (Time guardTime)
void SetLlc (Ptr< SatOrbiterLlc > llc)
Set the orbiter LLC associated to this orbiter MAC layer.
void SetReceiveNetDeviceCallback (SatOrbiterMac::ReceiveNetDeviceCallback cb)
void SetTransmitCallback (SatOrbiterMac::TransmitCallback cb)
void StartPeriodicTransmissions ()
Starts periodical transmissions.
virtual void StopPeriodicTransmissions ()
Stop periodic transmission, until a pacquet in enqued.
Public Member Functions inherited from ns3::SatMac
SatMac ()
Construct a SatMac.
SatMac (uint32_t satId, uint32_t beamId)
Construct a SatMac.
~SatMac ()
Destroy a SatMac.
virtual void Disable ()
Disable the MAC layer, i.e.
virtual void Enable ()
Enable the MAC layer, i.e.
Address GetAddress () const
Get MAC address.
uint32_t GetBeamId () const
Get beam ID of the object.
uint32_t GetSatId () const
Get sat ID of the object.
virtual void ReceiveQueueEvent (SatQueue::QueueEvent_t event, uint8_t flowIndex)
Receive a queue event:
uint32_t ReserveIdAndStoreCtrlMsgToContainer (Ptr< SatControlMessage > msg)
Reserve id and store the control message.
uint32_t SendCtrlMsgFromContainer (uint32_t sendId)
Send the control message from the container.
void SetBeamId (uint32_t beamId)
Set beam ID of the object.
void SetBeamSchedulerCallback (SatMac::BeamSchedulerCallback cb)
Set the beam scheduler callback.
void SetHandoverModule (Ptr< SatHandoverModule > handoverModule)
Set the handover module.
void SetLoraReceiveCallback (SatMac::LoraReceiveCallback cb)
Method to set receive callback.
virtual void SetNodeInfo (Ptr< SatNodeInfo > nodeInfo)
Set the node info.
void SetReadCtrlCallback (SatMac::ReadCtrlMsgCallback cb)
Method to set read control message callback.
void SetReceiveCallback (SatMac::ReceiveCallback cb)
Method to set receive callback.
void SetReserveCtrlCallback (SatMac::ReserveCtrlMsgCallback cb)
Method to set reserve control message id callback.
void SetRoutingUpdateCallback (SatMac::RoutingUpdateCallback cb)
Method to set the routing update callback.
virtual void SetSatelliteAddress (Address satelliteAddress)
Set the satellite MAC address on the other side of this link (if regenerative satellite).
void SetSatId (uint32_t satId)
Set sat ID of the object.
void SetSendCtrlCallback (SatMac::SendCtrlMsgCallback cb)
Method to set send control message callback.
void SetTransmitCallback (SatMac::TransmitCallback cb)
Method to set transmit callback.
void SetUpdateIslCallback (SatMac::UpdateIslCallback cb)
Method to set update ISL callback.
Static Public Member Functions
static TypeId GetTypeId (void)
inherited from Object
Static Public Member Functions inherited from ns3::SatMac
static TypeId GetTypeId (void)
Derived from Object.
Protected Member Functions
virtual Address GetRxUtAddress (Ptr< Packet > packet)=0
Get the UT address associated to this RX packet.
virtual SatEnums::SatLinkDir_t GetSatLinkRxDir ()=0
Get the link RX direction.
virtual SatEnums::SatLinkDir_t GetSatLinkTxDir ()=0
Get the link TX direction.
virtual bool HasPeer ()=0
Indicates if at least one device is connected in this beam.
virtual void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
virtual void SendPacket (SatPhy::PacketContainer_t packets, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo)
Send packets to lower layer by using a callback.
void StartTransmission (uint32_t carrierId)
Start sending a Packet Down the Wire.
Protected Member Functions inherited from ns3::SatMac
void DoDispose (void)
Dispose of SatMac.
void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
void SetTimeTag (SatPhy::PacketContainer_t packets)
Set SatMacTimeTag of packets.
Protected Attributes
TracedCallback< Ptr< SatBbFrame > > m_bbFrameTxTrace
Trace for transmitted BB frames.
uint32_t m_beamId
ID of beam for UT.
bool m_disableSchedulingIfNoDeviceConnected
If true, the periodic calls of StartTransmission are not called when no devices are connected to this MAC.
Ptr< SatFwdLinkScheduler > m_fwdScheduler
Scheduler for the forward link.
Time m_guardTime
Guard time for BB frames.
Ptr< SatOrbiterLlc > m_llc
LLC layer linked to this MAC.
bool m_periodicTransmissionEnabled
Indicated if periodic transmission is enabled.
ReceiveNetDeviceCallback m_rxNetDeviceCallback
uint32_t m_satId
ID of sat for UT.
TransmitCallback m_txCallback
Protected Attributes inherited from ns3::SatMac
Time m_beamEnabledTime
Time of the last beam enable event.
uint32_t m_beamId
The ID of the beam where mac belongs.
SatMac::BeamSchedulerCallback m_beamSchedulerCallback
Callback to get the SatBeamScheduler linked to a beam ID.
TracedCallback< Time > m_beamServiceTrace
Traced callback for beam being disabled and including service time.
SatEnums::RegenerationMode_t m_forwardLinkRegenerationMode
Regeneration mode on forward link.
Ptr< SatHandoverModule > m_handoverModule
Module used to perform handovers.
bool m_isRegenerative
Indicate if satellite is regeneration (at least LINK level) for TX.
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Time m_lastDelay
Last delay measurement.
Time m_lastLinkDelay
Last delay measurement for link.
std::queue< Time > m_lastSOF
Store last 3 SOF date for Forward messages, to insert in NCR packets.
std::queue< Ptr< SatNcrMessage > > m_ncrMessagesToSend
List of NCR control messages created but not sent yet.
bool m_ncrV2
Use of version 2 of NCR dates.
Ptr< SatNodeInfo > m_nodeInfo
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
Trace callback used for packet tracing.
SatMac::ReadCtrlMsgCallback m_readCtrlCallback
The read control message callback.
SatMac::ReserveCtrlMsgCallback m_reserveCtrlCallback
The reserve control message id callback.
SatEnums::RegenerationMode_t m_returnLinkRegenerationMode
Regeneration mode on return link.
SatMac::RoutingUpdateCallback m_routingUpdateCallback
Callback to update routing and ARP tables after a beam handover.
SatMac::ReceiveCallback m_rxCallback
The upper layer package receive callback.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
Traced callback for all received packets, including delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxJitterTrace
Traced callback for all received packets, including jitter information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkDelayTrace
Traced callback for all received packets, including link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkJitterTrace
Traced callback for all received packets, including link jitter information and the address of the senders.
SatMac::LoraReceiveCallback m_rxLoraCallback
The upper layer package receive callback.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced callback for all received packets, including the address of the senders.
Address m_satelliteAddress
MAC address of satellite on other side of the link.
uint32_t m_satId
The ID of the sat where mac belongs.
SatMac::SendCtrlMsgCallback m_sendCtrlCallback
The send control message callback.
SatMac::TransmitCallback m_txCallback
The lower layer packet transmit callback.
bool m_txEnabled
Flag indicating whether the MAC is enabled, i.e.
SatMac::UpdateIslCallback m_updateIslCallback
The update ISL routes callback.
Detailed Description
The SatOrbiterMac models the global link MAC layer of the satellite node.
Definition at line 47 of file satellite-orbiter-mac.h.
Member Typedef Documentation
BeamSchedulerCallback
typedef Callback<Ptr<SatBeamScheduler>, uint32_t, uint32_t> ns3::SatOrbiterMac::BeamSchedulerCallback
Callback to get the SatBeamScheduler from the beam ID for handover.
Definition at line 119 of file satellite-orbiter-mac.h.
ReceiveNetDeviceCallback
typedef Callback<void, SatPhy::PacketContainer_t, Ptr<SatSignalParameters> > ns3::SatOrbiterMac::ReceiveNetDeviceCallback
Definition at line 112 of file satellite-orbiter-mac.h.
TransmitCallback
typedef Callback<void, Ptr<SatSignalParameters> > ns3::SatOrbiterMac::TransmitCallback
Definition at line 107 of file satellite-orbiter-mac.h.
Constructor & Destructor Documentation
SatOrbiterMac() [1/2]
ns3::SatOrbiterMac::SatOrbiterMac (void)
Default constructor.
Definition at line 75 of file satellite-orbiter-mac.cc.
SatOrbiterMac() [2/2]
ns3::SatOrbiterMac::SatOrbiterMac (uint32_t satId, uint32_t beamId)
Construct a SatOrbiterMac.
This is the constructor for the SatOrbiterMac
Parameters
satId ID of sat for UT
beamId ID of beam for UT
Definition at line 81 of file satellite-orbiter-mac.cc.
~SatOrbiterMac()
ns3::SatOrbiterMac::~SatOrbiterMac () virtual
Destructor for SatOrbiterMac.
Definition at line 93 of file satellite-orbiter-mac.cc.
Member Function Documentation
AddPeer()
virtual bool ns3::SatOrbiterMac::AddPeer (Mac48Address address) pure virtual
Add a remote peer to this MAC.
Parameters
address The MAC address of the peer
Returns
True if the peer has been added, false otherwise
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
DoDispose()
void ns3::SatOrbiterMac::DoDispose (void) virtual
Dispose of this class instance.
Reimplemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
Definition at line 99 of file satellite-orbiter-mac.cc.
DoInitialize()
void ns3::SatOrbiterMac::DoInitialize (void) virtual
Reimplemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
Definition at line 106 of file satellite-orbiter-mac.cc.
EnquePacket()
virtual void ns3::SatOrbiterMac::EnquePacket (Ptr< Packet > packet) pure virtual
Add new packet to the LLC queue.
Parameters
packet Packets to be sent.
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
GetGuardTime()
Time ns3::SatOrbiterMac::GetGuardTime () const virtual
Definition at line 282 of file satellite-orbiter-mac.cc.
References m_guardTime.
Referenced by ns3::SatOrbiterFeederMac::GetTypeId(), and ns3::SatOrbiterUserMac::GetTypeId().
GetInstanceTypeId()
TypeId ns3::SatOrbiterMac::GetInstanceTypeId (void) const
Definition at line 68 of file satellite-orbiter-mac.cc.
References GetTypeId().
GetRxUtAddress()
virtual Address ns3::SatOrbiterMac::GetRxUtAddress (Ptr< Packet > packet) protected pure virtual
Get the UT address associated to this RX packet.
May be source or destination address depending on link used
Parameters
packet The packet to consider
Returns
The address of associated UT
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
Referenced by RxTraces().
GetSatLinkRxDir()
virtual SatEnums::SatLinkDir_t ns3::SatOrbiterMac::GetSatLinkRxDir () protected pure virtual
Get the link RX direction.
Must be implemented by child clases.
Returns
The link RX direction
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
GetSatLinkTxDir()
virtual SatEnums::SatLinkDir_t ns3::SatOrbiterMac::GetSatLinkTxDir () protected pure virtual
Get the link TX direction.
Must be implemented by child clases.
Returns
The link TX direction
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
Referenced by SendPacket().
GetTypeId()
TypeId ns3::SatOrbiterMac::GetTypeId (void) static
inherited from Object
Definition at line 47 of file satellite-orbiter-mac.cc.
References m_bbFrameTxTrace, and m_disableSchedulingIfNoDeviceConnected.
Referenced by GetInstanceTypeId().
HasPeer()
virtual bool ns3::SatOrbiterMac::HasPeer () protected pure virtual
Indicates if at least one device is connected in this beam.
Returns
True if at least a device is connected, false otherwise
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
Referenced by StartPeriodicTransmissions().
RemovePeer()
virtual bool ns3::SatOrbiterMac::RemovePeer (Mac48Address address) pure virtual
Remove a remote peer from this MAC.
Parameters
address The MAC address of the peer
Returns
True if the peer has been removed, false otherwise
Implemented in ns3::SatOrbiterUserMac, and ns3::SatOrbiterFeederMac.
RxTraces()
void ns3::SatOrbiterMac::RxTraces (SatPhy::PacketContainer_t packets) protected virtual
Invoke the Rx trace source for each received packet.
Parameters
packets Container of the pointers to the packets received.
Definition at line 224 of file satellite-orbiter-mac.cc.
References ns3::SatMacTag::GetDestAddress(), GetRxUtAddress(), ns3::SatMacLinkTimeTag::GetSenderLinkTimestamp(), ns3::SatMac::m_isStatisticsTagsEnabled, ns3::SatMac::m_lastLinkDelay, ns3::SatMac::m_nodeInfo, ns3::SatMac::m_rxLinkDelayTrace, ns3::SatMac::m_rxLinkJitterTrace, and ns3::SatMac::m_rxTrace.
Referenced by ns3::SatOrbiterFeederMac::Receive(), and ns3::SatOrbiterUserMac::Receive().
SendPacket()
void ns3::SatOrbiterMac::SendPacket (SatPhy::PacketContainer_t packets, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo) protected virtual
Send packets to lower layer by using a callback.
Parameters
packets Packets to be sent.
carrierId ID of the carrier used for transmission.
duration Duration of the physical layer transmission.
txInfo Additional parameterization for burst transmission.
Reimplemented from ns3::SatMac.
Definition at line 191 of file satellite-orbiter-mac.cc.
References ns3::SatUtils::GetPacketInfo(), GetSatLinkTxDir(), ns3::SatEnums::LL_MAC, m_beamId, ns3::SatMac::m_nodeInfo, ns3::SatMac::m_packetTrace, m_satId, m_txCallback, ns3::SatEnums::PACKET_SENT, and ns3::SatMac::SetTimeTag().
Referenced by StartTransmission().
SetBeamSchedulerCallback()
void ns3::SatOrbiterMac::SetBeamSchedulerCallback (SatOrbiterMac::BeamSchedulerCallback cb)
Set the beam scheduler callback.
Parameters
cb Callback to get the SatBeamScheduler
SetFwdScheduler()
void ns3::SatOrbiterMac::SetFwdScheduler (Ptr< SatFwdLinkScheduler > fwdScheduler)
Method to set link scheduler (forward or SCPC)
Parameters
The scheduler to use
Definition at line 270 of file satellite-orbiter-mac.cc.
References m_fwdScheduler.
SetGuardTime()
void ns3::SatOrbiterMac::SetGuardTime (Time guardTime) virtual
Definition at line 288 of file satellite-orbiter-mac.cc.
References m_guardTime.
Referenced by ns3::SatOrbiterFeederMac::GetTypeId(), and ns3::SatOrbiterUserMac::GetTypeId().
SetLlc()
void ns3::SatOrbiterMac::SetLlc (Ptr< SatOrbiterLlc > llc)
Set the orbiter LLC associated to this orbiter MAC layer.
Definition at line 276 of file satellite-orbiter-mac.cc.
References m_llc.
SetReceiveNetDeviceCallback()
void ns3::SatOrbiterMac::SetReceiveNetDeviceCallback (SatOrbiterMac::ReceiveNetDeviceCallback cb)
Definition at line 301 of file satellite-orbiter-mac.cc.
References m_rxNetDeviceCallback.
SetTransmitCallback()
void ns3::SatOrbiterMac::SetTransmitCallback (SatOrbiterMac::TransmitCallback cb)
Definition at line 294 of file satellite-orbiter-mac.cc.
References m_txCallback.
StartPeriodicTransmissions()
void ns3::SatOrbiterMac::StartPeriodicTransmissions ()
Starts periodical transmissions.
Called when MAC is wanted to take care of periodic sending.
Definition at line 113 of file satellite-orbiter-mac.cc.
References HasPeer(), m_beamId, m_disableSchedulingIfNoDeviceConnected, m_fwdScheduler, m_llc, m_periodicTransmissionEnabled, and StartTransmission().
Referenced by ns3::SatOrbiterUserMac::AddPeer().
StartTransmission()
void ns3::SatOrbiterMac::StartTransmission (uint32_t carrierId) protected
Start sending a Packet Down the Wire.
The StartTransmission method is used internally in the SatOrbiterMac to begin the process of sending a packet out on the PHY layer.
Parameters
carrierId id of the carrier.
Returns
true if success, false on failure
Decrease a guard time from BB frame duration.
Orbiter MAC is disabled, thus get the duration of the default BB frame and try again then.
Definition at line 142 of file satellite-orbiter-mac.cc.
References ns3::SatSignalParameters::txInfo_s::frameType, m_bbFrameTxTrace, m_disableSchedulingIfNoDeviceConnected, m_fwdScheduler, m_guardTime, m_periodicTransmissionEnabled, ns3::SatMac::m_txEnabled, ns3::SatSignalParameters::txInfo_s::modCod, ns3::SatEnums::PACKET_TYPE_DEDICATED_ACCESS, ns3::SatSignalParameters::txInfo_s::packetType, SendPacket(), ns3::SatSignalParameters::txInfo_s::sliceId, and ns3::SatSignalParameters::txInfo_s::waveformId.
Referenced by StartPeriodicTransmissions().
StopPeriodicTransmissions()
void ns3::SatOrbiterMac::StopPeriodicTransmissions () virtual
Stop periodic transmission, until a pacquet in enqued.
Definition at line 308 of file satellite-orbiter-mac.cc.
References m_llc, and m_periodicTransmissionEnabled.
Referenced by ns3::SatOrbiterUserMac::RemovePeer().
Member Data Documentation
m_bbFrameTxTrace
TracedCallback<Ptr<SatBbFrame> > ns3::SatOrbiterMac::m_bbFrameTxTrace protected
Trace for transmitted BB frames.
Definition at line 240 of file satellite-orbiter-mac.h.
Referenced by GetTypeId(), and StartTransmission().
m_beamId
uint32_t ns3::SatOrbiterMac::m_beamId protected
ID of beam for UT.
Definition at line 230 of file satellite-orbiter-mac.h.
Referenced by ns3::SatOrbiterUserMac::AddPeer(), ns3::SatOrbiterUserMac::RemovePeer(), SendPacket(), and StartPeriodicTransmissions().
m_disableSchedulingIfNoDeviceConnected
bool ns3::SatOrbiterMac::m_disableSchedulingIfNoDeviceConnected protected
If true, the periodic calls of StartTransmission are not called when no devices are connected to this MAC.
Definition at line 209 of file satellite-orbiter-mac.h.
Referenced by ns3::SatOrbiterUserMac::AddPeer(), GetTypeId(), ns3::SatOrbiterUserMac::RemovePeer(), StartPeriodicTransmissions(), and StartTransmission().
m_fwdScheduler
Ptr<SatFwdLinkScheduler> ns3::SatOrbiterMac::m_fwdScheduler protected
Scheduler for the forward link.
Definition at line 214 of file satellite-orbiter-mac.h.
Referenced by ns3::SatOrbiterFeederMac::ReceiveSignalingPacket(), ns3::SatOrbiterUserMac::ReceiveSignalingPacket(), SetFwdScheduler(), StartPeriodicTransmissions(), and StartTransmission().
m_guardTime
Time ns3::SatOrbiterMac::m_guardTime protected
Guard time for BB frames.
The guard time is modeled by shortening the duration of a BB frame by a m_guardTime set by an attribute.
Definition at line 220 of file satellite-orbiter-mac.h.
Referenced by GetGuardTime(), SetGuardTime(), and StartTransmission().
m_llc
Ptr<SatOrbiterLlc> ns3::SatOrbiterMac::m_llc protected
LLC layer linked to this MAC.
Definition at line 235 of file satellite-orbiter-mac.h.
Referenced by ns3::SatOrbiterFeederMac::EnquePacket(), ns3::SatOrbiterUserMac::EnquePacket(), SetLlc(), StartPeriodicTransmissions(), and StopPeriodicTransmissions().
m_periodicTransmissionEnabled
bool ns3::SatOrbiterMac::m_periodicTransmissionEnabled protected
Indicated if periodic transmission is enabled.
Definition at line 248 of file satellite-orbiter-mac.h.
Referenced by ns3::SatOrbiterFeederMac::EnquePacket(), ns3::SatOrbiterUserMac::EnquePacket(), StartPeriodicTransmissions(), StartTransmission(), and StopPeriodicTransmissions().
m_rxNetDeviceCallback
ReceiveNetDeviceCallback ns3::SatOrbiterMac::m_rxNetDeviceCallback protected
Definition at line 243 of file satellite-orbiter-mac.h.
Referenced by ns3::SatOrbiterFeederMac::Receive(), ns3::SatOrbiterUserMac::Receive(), and SetReceiveNetDeviceCallback().
m_satId
uint32_t ns3::SatOrbiterMac::m_satId protected
ID of sat for UT.
Definition at line 225 of file satellite-orbiter-mac.h.
Referenced by SendPacket().
m_txCallback
TransmitCallback ns3::SatOrbiterMac::m_txCallback protected
Definition at line 242 of file satellite-orbiter-mac.h.
Referenced by SendPacket(), and SetTransmitCallback().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-orbiter-mac.h
/builds/sns3/satellite/satellite/model/satellite-orbiter-mac.cc