SNS3
ns3::SatMacTag Class Reference
This class implements a tag that carries the satellite MAC specific information, such as source and destination MAC address.
#include "satellite-mac-tag.h"
Public Member Functions
SatMacTag ()
Default constructor.
~SatMacTag ()
Destructor for SatMacTag.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatMacTag.
Mac48Address GetDestAddress (void) const
Get destination MAC address.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
virtual uint32_t GetSerializedSize (void) const
Get serialized size of SatMacTag.
Mac48Address GetSourceAddress (void) const
Get source MAC address.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatMacTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatMacTag.
void SetDestAddress (Mac48Address dest)
Set destination MAC address.
void SetSourceAddress (Mac48Address source)
Set source MAC address.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_destAddress
Mac48Address m_sourceAddress
Static Private Attributes
static const uint32_t ADDRESS_LENGHT = 6
Detailed Description
This class implements a tag that carries the satellite MAC specific information, such as source and destination MAC address.
Definition at line 39 of file satellite-mac-tag.h.
Constructor & Destructor Documentation
SatMacTag()
ns3::SatMacTag::SatMacTag ()
Default constructor.
Definition at line 35 of file satellite-mac-tag.cc.
~SatMacTag()
ns3::SatMacTag::~SatMacTag ()
Destructor for SatMacTag.
Definition at line 40 of file satellite-mac-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatMacTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatMacTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 111 of file satellite-mac-tag.cc.
References ADDRESS_LENGHT, m_destAddress, and m_sourceAddress.
GetDestAddress()
Mac48Address ns3::SatMacTag::GetDestAddress (void) const
Get destination MAC address.
Returns
Destination MAC address
Definition at line 68 of file satellite-mac-tag.cc.
References m_destAddress.
Referenced by ns3::SatUtils::GetPacketInfo(), ns3::SatPhyRxCarrier::GetReceiveParams(), PrintBbFrameInfo(), ns3::SatOrbiterFeederMac::Receive(), ns3::SatOrbiterUserMac::Receive(), ns3::SatGwMac::Receive(), ns3::SatUtMac::Receive(), ns3::SatGenericStreamEncapsulatorArq::ReceivePdu(), ns3::SatGenericStreamEncapsulator::ReceivePdu(), ns3::SatReturnLinkEncapsulatorArq::ReceivePdu(), ns3::SatReturnLinkEncapsulator::ReceivePdu(), ns3::SatUtMac::ReceiveSignalingPacket(), ns3::SatGwMac::ReceiveSignalingPacket(), ns3::SatMac::RxTraces(), ns3::SatOrbiterMac::RxTraces(), and ns3::SatChannel::StartTx().
GetInstanceTypeId()
TypeId ns3::SatMacTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 53 of file satellite-mac-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SatMacTag::GetSerializedSize (void) const virtual
Get serialized size of SatMacTag.
Returns
Serialized size in bytes
Definition at line 89 of file satellite-mac-tag.cc.
References ADDRESS_LENGHT.
GetSourceAddress()
Mac48Address ns3::SatMacTag::GetSourceAddress (void) const
Get source MAC address.
Returns
Source MAC address
Definition at line 82 of file satellite-mac-tag.cc.
References m_sourceAddress.
Referenced by ns3::SatUtils::GetPacketInfo(), ns3::SatPhyRxCarrier::GetReceiveParams(), ns3::SatChannel::GetSourceAddress(), ns3::SatOrbiterFeederMac::Receive(), ns3::SatOrbiterUserMac::Receive(), ns3::SatGwMac::Receive(), ns3::SatUtMac::Receive(), ns3::SatOrbiterFeederMac::ReceiveSignalingPacket(), ns3::SatOrbiterUserMac::ReceiveSignalingPacket(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetTypeId()
TypeId ns3::SatMacTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 46 of file satellite-mac-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatMacTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatMacTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 125 of file satellite-mac-tag.cc.
References m_destAddress, and m_sourceAddress.
Serialize()
void ns3::SatMacTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatMacTag.
Parameters
i Buffer in which the information is serialized
Definition at line 97 of file satellite-mac-tag.cc.
References ADDRESS_LENGHT, m_destAddress, and m_sourceAddress.
SetDestAddress()
void ns3::SatMacTag::SetDestAddress (Mac48Address dest)
Set destination MAC address.
Parameters
dest Destination MAC address
Definition at line 61 of file satellite-mac-tag.cc.
References m_destAddress.
Referenced by ns3::SatUtMac::DoTransmit(), ns3::SatOrbiterFeederMac::EnquePacket(), ns3::SatOrbiterUserMac::EnquePacket(), ns3::SatBaseEncapsulator::EnquePdu(), ns3::SatReturnLinkEncapsulator::EnquePdu(), ns3::SatFwdLinkSchedulerDefault::GetNextFrame(), ns3::SatFwdLinkSchedulerTimeSlicing::GetNextFrame(), ns3::SatScpcScheduler::GetNextFrame(), ns3::SatGenericStreamEncapsulatorArq::NotifyTxOpportunity(), ns3::SatGenericStreamEncapsulator::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulator::NotifyTxOpportunity(), ns3::LorawanMacEndDeviceClassA::Receive(), ns3::LorawanGroundMacGateway::Send(), ns3::LorawanOrbiterMacGateway::Send(), ns3::LorawanMacGateway::Send(), ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder(), ns3::SatMac::SendPacket(), and ns3::LorawanMacEndDeviceClassA::SendToPhy().
SetSourceAddress()
void ns3::SatMacTag::SetSourceAddress (Mac48Address source)
Set source MAC address.
Parameters
source Source MAC address
Definition at line 75 of file satellite-mac-tag.cc.
References m_sourceAddress.
Referenced by ns3::SatUtMac::DoTransmit(), ns3::SatOrbiterFeederMac::EnquePacket(), ns3::SatOrbiterUserMac::EnquePacket(), ns3::SatBaseEncapsulator::EnquePdu(), ns3::SatReturnLinkEncapsulator::EnquePdu(), ns3::SatFwdLinkSchedulerDefault::GetNextFrame(), ns3::SatFwdLinkSchedulerTimeSlicing::GetNextFrame(), ns3::SatScpcScheduler::GetNextFrame(), ns3::SatGenericStreamEncapsulatorArq::NotifyTxOpportunity(), ns3::SatGenericStreamEncapsulator::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulator::NotifyTxOpportunity(), ns3::LorawanGroundMacGateway::Send(), ns3::LorawanOrbiterMacGateway::Send(), ns3::LorawanMacGateway::Send(), ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder(), and ns3::LorawanMacEndDeviceClassA::SendToPhy().
Member Data Documentation
ADDRESS_LENGHT
const uint32_t ns3::SatMacTag::ADDRESS_LENGHT = 6 static private
Definition at line 113 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetSerializedSize(), and Serialize().
m_destAddress
Mac48Address ns3::SatMacTag::m_destAddress private
Definition at line 115 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetDestAddress(), Print(), Serialize(), and SetDestAddress().
m_sourceAddress
Mac48Address ns3::SatMacTag::m_sourceAddress private
Definition at line 116 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetSourceAddress(), Print(), Serialize(), and SetSourceAddress().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-mac-tag.h
/builds/sns3/satellite/satellite/model/satellite-mac-tag.cc