SNS3
SatRegenerationTest4 Class Reference
'Regeneration, test 4' test case implementation.
Public Member Functions
SatRegenerationTest4 ()
virtual ~SatRegenerationTest4 ()
Private Member Functions
virtual void DoRun (void)
bool HasSinkInstalled (Ptr< Node > node, uint16_t port)
void OrbiterDevGwRxTraceCb (Ptr< const Packet > packet, const Address &)
void OrbiterDevGwTxTraceCb (Ptr< const Packet > packet)
void OrbiterDevUtRxTraceCb (Ptr< const Packet > packet, const Address &)
void OrbiterDevUtTxTraceCb (Ptr< const Packet > packet)
Private Attributes
Ptr< SatHelper > m_helper
uint32_t m_totalReceivedGw
uint32_t m_totalReceivedUt
uint32_t m_totalSentGw
uint32_t m_totalSentUt
Detailed Description
'Regeneration, test 4' test case implementation.
This case tests link regeneration on satellite. It is based on a LARGER scenario.
Expected result: No bytes sent or received on FWD Same number of bytes sent and received on RTN
Definition at line 886 of file satellite-regeneration-test.cc.
Constructor & Destructor Documentation
SatRegenerationTest4()
SatRegenerationTest4::SatRegenerationTest4 ()
Definition at line 952 of file satellite-regeneration-test.cc.
References m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, and m_totalSentUt.
~SatRegenerationTest4()
SatRegenerationTest4::~SatRegenerationTest4 () virtual
Definition at line 963 of file satellite-regeneration-test.cc.
Member Function Documentation
DoRun()
void SatRegenerationTest4::DoRun (void) private virtual
Set regeneration mode
Set simulation output details
Definition at line 971 of file satellite-regeneration-test.cc.
References HasSinkInstalled(), m_helper, m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, m_totalSentUt, OrbiterDevGwRxTraceCb(), OrbiterDevGwTxTraceCb(), OrbiterDevUtRxTraceCb(), and OrbiterDevUtTxTraceCb().
HasSinkInstalled()
bool SatRegenerationTest4::HasSinkInstalled (Ptr< Node > node, uint16_t port) private
Definition at line 933 of file satellite-regeneration-test.cc.
Referenced by DoRun().
OrbiterDevGwRxTraceCb()
void SatRegenerationTest4::OrbiterDevGwRxTraceCb (Ptr< const Packet > packet, const Address &) private
Definition at line 921 of file satellite-regeneration-test.cc.
References m_totalReceivedGw.
Referenced by DoRun().
OrbiterDevGwTxTraceCb()
void SatRegenerationTest4::OrbiterDevGwTxTraceCb (Ptr< const Packet > packet) private
Definition at line 909 of file satellite-regeneration-test.cc.
References m_totalSentGw.
Referenced by DoRun().
OrbiterDevUtRxTraceCb()
void SatRegenerationTest4::OrbiterDevUtRxTraceCb (Ptr< const Packet > packet, const Address & address) private
Definition at line 927 of file satellite-regeneration-test.cc.
References m_totalReceivedUt.
Referenced by DoRun().
OrbiterDevUtTxTraceCb()
void SatRegenerationTest4::OrbiterDevUtTxTraceCb (Ptr< const Packet > packet) private
Definition at line 915 of file satellite-regeneration-test.cc.
References m_totalSentUt.
Referenced by DoRun().
Member Data Documentation
m_helper
Ptr<SatHelper> SatRegenerationTest4::m_helper private
Definition at line 900 of file satellite-regeneration-test.cc.
Referenced by DoRun().
m_totalReceivedGw
uint32_t SatRegenerationTest4::m_totalReceivedGw private
Definition at line 904 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and OrbiterDevGwRxTraceCb().
m_totalReceivedUt
uint32_t SatRegenerationTest4::m_totalReceivedUt private
Definition at line 905 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and OrbiterDevUtRxTraceCb().
m_totalSentGw
uint32_t SatRegenerationTest4::m_totalSentGw private
Definition at line 902 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and OrbiterDevGwTxTraceCb().
m_totalSentUt
uint32_t SatRegenerationTest4::m_totalSentUt private
Definition at line 903 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and OrbiterDevUtTxTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-regeneration-test.cc