SNS3
ns3::SatAddressE2ETag Class Reference
This class implements a tag that carries the satellite MAC of GW and UT.
#include "satellite-mac-tag.h"
Public Member Functions
SatAddressE2ETag ()
Default constructor.
~SatAddressE2ETag ()
Destructor for SatMacTag.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatMacTag.
Mac48Address GetE2EDestAddress (void) const
Get E2E destination MAC address.
Mac48Address GetE2ESourceAddress (void) const
Get E2E source MAC address.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
virtual uint32_t GetSerializedSize (void) const
Get serialized size of SatMacTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatMacTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatMacTag.
void SetE2EDestAddress (Mac48Address e2eDestAddress)
Set E2E destination MAC address.
void SetE2ESourceAddress (Mac48Address e2eSourceAddress)
Set E2E source MAC address.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint32_t SIZE = 12
Private Attributes
Mac48Address m_e2eDestAddress
Mac48Address m_e2eSourceAddress
Static Private Attributes
static const uint32_t ADDRESS_LENGHT = 6
Detailed Description
This class implements a tag that carries the satellite MAC of GW and UT.
It is used for regenerative cases to update MAC address on satellite when packet is forwarded between uplink and downlink.
Definition at line 125 of file satellite-mac-tag.h.
Constructor & Destructor Documentation
SatAddressE2ETag()
ns3::SatAddressE2ETag::SatAddressE2ETag ()
Default constructor.
Definition at line 133 of file satellite-mac-tag.cc.
~SatAddressE2ETag()
ns3::SatAddressE2ETag::~SatAddressE2ETag ()
Destructor for SatMacTag.
Definition at line 138 of file satellite-mac-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatAddressE2ETag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatMacTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 210 of file satellite-mac-tag.cc.
References ADDRESS_LENGHT, m_e2eDestAddress, and m_e2eSourceAddress.
GetE2EDestAddress()
Mac48Address ns3::SatAddressE2ETag::GetE2EDestAddress (void) const
Get E2E destination MAC address.
Returns
E2E destination MAC address
Definition at line 167 of file satellite-mac-tag.cc.
References m_e2eDestAddress.
Referenced by ns3::SatOrbiterFeederMac::EnquePacket(), ns3::SatOrbiterUserMac::EnquePacket(), ns3::SatOrbiterUserPhy::GetE2EDestinationAddress(), ns3::SatPhyRxCarrier::GetReceiveParams(), ns3::SatOrbiterFeederMac::GetRxUtAddress(), ns3::SatOrbiterNetDevice::GetRxUtAddress(), ns3::SatPhy::ModcodTrace(), ns3::SatOrbiterFeederMac::Receive(), ns3::SatOrbiterUserMac::Receive(), ns3::SatGwMac::Receive(), ns3::SatUtMac::Receive(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), and ns3::SatOrbiterFeederPhy::RxTraces().
GetE2ESourceAddress()
Mac48Address ns3::SatAddressE2ETag::GetE2ESourceAddress (void) const
Get E2E source MAC address.
Returns
E2E source MAC address
Definition at line 181 of file satellite-mac-tag.cc.
References m_e2eSourceAddress.
Referenced by ns3::SatPhyRxCarrier::GetReceiveParams(), ns3::SatOrbiterUserMac::GetRxUtAddress(), ns3::SatOrbiterNetDevice::GetRxUtAddress(), ns3::SatPhy::ModcodTrace(), ns3::SatGwMac::Receive(), ns3::SatUtMac::Receive(), ns3::SatUtMac::ReceiveSignalingPacket(), ns3::SatGwMac::ReceiveSignalingPacket(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetInstanceTypeId()
TypeId ns3::SatAddressE2ETag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 152 of file satellite-mac-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SatAddressE2ETag::GetSerializedSize (void) const virtual
Get serialized size of SatMacTag.
Returns
Serialized size in bytes
Definition at line 188 of file satellite-mac-tag.cc.
References ADDRESS_LENGHT.
GetTypeId()
TypeId ns3::SatAddressE2ETag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 144 of file satellite-mac-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatAddressE2ETag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatMacTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 224 of file satellite-mac-tag.cc.
References m_e2eDestAddress, and m_e2eSourceAddress.
Serialize()
void ns3::SatAddressE2ETag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatMacTag.
Parameters
i Buffer in which the information is serialized
Definition at line 196 of file satellite-mac-tag.cc.
References ADDRESS_LENGHT, m_e2eDestAddress, and m_e2eSourceAddress.
SetE2EDestAddress()
void ns3::SatAddressE2ETag::SetE2EDestAddress (Mac48Address e2eDestAddress)
Set E2E destination MAC address.
Parameters
e2eDestAddress E2E destination MAC address
Definition at line 160 of file satellite-mac-tag.cc.
References m_e2eDestAddress.
Referenced by ns3::SatUtMac::DoTransmit(), ns3::SatGwLlc::Enque(), ns3::SatLlc::Enque(), ns3::SatUtLlc::Enque(), ns3::SatFwdLinkSchedulerDefault::GetNextFrame(), ns3::SatFwdLinkSchedulerTimeSlicing::GetNextFrame(), ns3::SatScpcScheduler::GetNextFrame(), ns3::SatGenericStreamEncapsulatorArq::NotifyTxOpportunity(), ns3::SatGenericStreamEncapsulator::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulator::NotifyTxOpportunity(), ns3::LorawanMacEndDeviceClassA::Receive(), ns3::LorawanGroundMacGateway::Send(), ns3::LorawanMacGateway::Send(), ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder(), and ns3::LorawanMacEndDeviceClassA::SendToPhy().
SetE2ESourceAddress()
void ns3::SatAddressE2ETag::SetE2ESourceAddress (Mac48Address e2eSourceAddress)
Set E2E source MAC address.
Parameters
e2eSourceAddress E2E source MAC address
Definition at line 174 of file satellite-mac-tag.cc.
References m_e2eSourceAddress.
Referenced by ns3::SatUtMac::DoTransmit(), ns3::SatGwLlc::Enque(), ns3::SatLlc::Enque(), ns3::SatUtLlc::Enque(), ns3::SatFwdLinkSchedulerDefault::GetNextFrame(), ns3::SatFwdLinkSchedulerTimeSlicing::GetNextFrame(), ns3::SatScpcScheduler::GetNextFrame(), ns3::SatGenericStreamEncapsulatorArq::NotifyTxOpportunity(), ns3::SatGenericStreamEncapsulator::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulator::NotifyTxOpportunity(), ns3::LorawanGroundMacGateway::Send(), ns3::LorawanMacGateway::Send(), ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder(), and ns3::LorawanMacEndDeviceClassA::SendToPhy().
Member Data Documentation
ADDRESS_LENGHT
const uint32_t ns3::SatAddressE2ETag::ADDRESS_LENGHT = 6 static private
Definition at line 201 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetSerializedSize(), and Serialize().
m_e2eDestAddress
Mac48Address ns3::SatAddressE2ETag::m_e2eDestAddress private
Definition at line 203 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetE2EDestAddress(), Print(), Serialize(), and SetE2EDestAddress().
m_e2eSourceAddress
Mac48Address ns3::SatAddressE2ETag::m_e2eSourceAddress private
Definition at line 204 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetE2ESourceAddress(), Print(), Serialize(), and SetE2ESourceAddress().
SIZE
const uint32_t ns3::SatAddressE2ETag::SIZE = 12 static
Definition at line 128 of file satellite-mac-tag.h.
Referenced by ns3::SatGwHelperDvb::Install(), and ns3::SatUtHelperDvb::Install().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-mac-tag.h
/builds/sns3/satellite/satellite/model/satellite-mac-tag.cc