SNS3
ns3::SatOrbiterFeederPhy Class Reference
The SatOrbiterFeederPhy models the feeder link physical layer of the satellite node.
#include "satellite-orbiter-feeder-phy.h"
Public Types
typedef void(* QueueSizeCallback) (uint32_t size, const Address &from)
Callback signature for QueueSizeBytes and QueueSizePackets trace source.
Public Types inherited from ns3::SatPhy
typedef Callback< void, uint32_t, uint32_t, uint32_t, uint8_t, double > AverageNormalizedOfferedLoadCallback
typedef Callback< SatChannelPair::ChannelPair_t, uint32_t, uint32_t > ChannelPairGetterCallback
Callback for retrieving a pair of SatChannel associated to a beam.
typedef Callback< void, uint32_t, uint32_t, Address, Address, double, bool > CnoCallback
typedef SatPhyRxCarrierConf::ErrorModel ErrorModel
Define ErrorModel in SatPhy.
typedef SatPhyRxCarrierConf::InterferenceEliminationModel InterferenceEliminationModel
Define InterferenceEliminationModel in SatPhy.
typedef SatPhyRxCarrierConf::InterferenceModel InterferenceModel
Define InterferenceModel in SatPhy.
typedef SatSignalParameters::PacketsInBurst_t PacketContainer_t
Define PacketContainer in SatPhy.
typedef Callback< void, PacketContainer_t, Ptr< SatSignalParameters > > ReceiveCallback
Public Member Functions
SatOrbiterFeederPhy (SatPhy::CreateParam_t &params, Ptr< SatLinkResults > linkResults, SatPhyRxCarrierConf::RxCarrierCreateParams_s parameters, Ptr< SatSuperframeConf > superFrameConf)
SatOrbiterFeederPhy (void)
Default constructor.
virtual ~SatOrbiterFeederPhy ()
Destructor for SatOrbiterFeederPhy.
virtual void DoDispose (void)
Dispose of this class instance.
virtual void DoInitialize (void)
Initialization of SatPhy.
virtual double GetAdditionalInterference ()
Get additional interference, used to compute final SINR at RX.
TypeId GetInstanceTypeId (void) const
virtual void Receive (Ptr< SatSignalParameters > rxParams, bool phyError)
Receives packets from lower layer.
virtual void SendPduWithParams (Ptr< SatSignalParameters > rxParams)
Send Pdu to the PHY tx module (for satellite switch packet forwarding)
Public Member Functions inherited from ns3::SatPhy
SatPhy (CreateParam_t &params)
Constructor to create PHY objects with parameters.
SatPhy (void)
Default constructor.
virtual ~SatPhy ()
Destructor.
void AverageNormalizedOfferedRandomAccessLoadInfo (uint32_t satId, uint32_t beamId, uint32_t carrierId, uint8_t allocationChannelId, double averageNormalizedOfferedLoad)
Function for getting the normalized offered load of the specific random access allocation channel.
void BeginEndScheduling ()
Begin frame/window end scheduling for processes utilizing frame length as interval.
double CalculateSinr (double sinr, double otherInterference)
Calculate final SINR with PHY specific parameters and given calculated SINR.
void CnoInfo (uint32_t satId, uint32_t beamId, Address source, Address destination, double cno, bool isSatelliteMac)
Function for getting the C/NO information.
void ConfigureRxCarriers (Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatSuperframeConf > superFrameConf)
Configure Rx carriers.
double GetDefaultFading () const
Get the default fading of the PHY.
TypeId GetInstanceTypeId (void) const
Derived from Object.
virtual Ptr< SatPhyRx > GetPhyRx () const
Get the SatPhyRx pointer.
virtual Ptr< SatPhyTx > GetPhyTx () const
Get the SatPhyTx pointer.
double GetRxAntennaGainDb () const
Get the maximum antenna gain of the receiver in dB.
double GetRxAntennaLossDb () const
Get the antenna loss of the receiver in dB.
double GetRxNoiseTemperatureDbk () const
Get the noise temperature of the receiver in dbK.
double GetTxAntennaGainDb () const
Get the maximum antenna gain of the transmitter in dB.
double GetTxAntennaLossDb () const
Get the antenna loss of the transmitter in dB.
Ptr< SatChannel > GetTxChannel ()
Get the Tx satellite channel.
double GetTxMaxPowerDbw () const
Get the maximum transmit power of the transmitter in dB.
double GetTxOboLossDb () const
Get the OBO loss of the transmitter in dB.
double GetTxOutputLossDb () const
Get the output loss of the transmitter in dB.
double GetTxPointingLossDb () const
Get the pointing loss of the transmitter in dB.
void Initialize ()
Initialize phy.
virtual void SendPdu (PacketContainer_t, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo)
Send Pdu to the PHY tx module (for initial transmissions from either UT or GW)
bool SetBeamId (uint32_t beamId)
Set the beamId this PHY is connected with.
void SetChannelPairGetterCallback (SatPhy::ChannelPairGetterCallback cb)
Set the channel pair getter callback.
void SetDefaultFading (double fading)
Set the default fading of the PHY.
void SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Set the node info class.
virtual void SetPhyRx (Ptr< SatPhyRx > phyRx)
Set the SatPhyRx module.
virtual void SetPhyTx (Ptr< SatPhyTx > phyTx)
Set the SatPhyTx module.
void SetRxAntennaGainDb (double gainDb)
Set the maximum antenna gain of the receiver in dB.
virtual void SetRxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility)
Set the receive antenna gain pattern.
void SetRxAntennaLossDb (double lossDb)
Set the antenna loss of the receiver in dB.
void SetRxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetRxNoiseTemperatureDbk (double temperatureDbk)
Set the noise temperature of the receiver in dbK.
void SetSatId (uint32_t satId)
Set the satId this PHY is connected with.
void SetTxAntennaGainDb (double gainDb)
Set the maximum antenna gain of the transmitter in dB.
virtual void SetTxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility)
Set the transmit antenna gain pattern.
void SetTxAntennaLossDb (double lossDb)
Set the antenna loss of the transmitter in dB.
void SetTxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetTxMaxPowerDbw (double powerDb)
Set the maximum transmit power of the transmitter in dB.
void SetTxOboLossDb (double lossDb)
Set the OBO loss of the transmitter in dB.
void SetTxOutputLossDb (double lossDb)
Set the output loss of the transmitter in dB.
void SetTxPointingLossDb (double lossDb)
Set the pointing loss of the transmitter in dB.
Static Public Member Functions
static TypeId GetTypeId (void)
inherited from Object
Static Public Member Functions inherited from ns3::SatPhy
static TypeId GetTypeId (void)
Derived from Object.
Protected Member Functions
virtual SatEnums::SatLinkDir_t GetSatLinkRxDir ()
Get the link RX direction.
virtual SatEnums::SatLinkDir_t GetSatLinkTxDir ()
Get the link TX direction.
virtual void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
Protected Member Functions inherited from ns3::SatPhy
void ModcodTrace (Ptr< SatSignalParameters > rxParams)
Invoke the RxLinkModcod trace source for each received packet.
void SetTimeTag (SatPhy::PacketContainer_t packets)
Set SatPhyTimeTag of packets.
Protected Attributes
TracedCallback< uint32_t, const Address & > m_queueSizeBytesTrace
Traced callback to monitor RTN feeder queue size in bytes.
TracedCallback< uint32_t, const Address & > m_queueSizePacketsTrace
Traced callback to monitor RTN feeder queue size in packets.
Protected Attributes inherited from ns3::SatPhy
uint32_t m_beamId
Beam ID.
double m_eirpWoGainW
Calculated EIRP without gain in W.
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Time m_lastDelay
Last delay measurement.
Time m_lastLinkDelay
Last delay measurement for link.
Ptr< SatNodeInfo > m_nodeInfo
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
Trace callback used for packet tracing:
Ptr< SatPhyRx > m_phyRx
Pointer to internal SatPhyRx instance.
Ptr< SatPhyTx > m_phyTx
Pointer to internal SatPhyTx instance.
SatPhy::ChannelPairGetterCallback m_retrieveChannelPair
Callback for retrieving SatChannel pairs by beam.
SatPhy::ReceiveCallback m_rxCallback
The upper layer package receive callback.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
Traced callback for all received packets, including delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxJitterTrace
Traced callback for all received packets, including jitter information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkDelayTrace
Traced callback for all received packets, including link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkJitterTrace
Traced callback for all received packets, including link jitter information and the address of the senders.
TracedCallback< uint32_t, const Address & > m_rxLinkModcodTrace
Traced callback for all received packets, including link MODCOD information and the address of the senders.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced callback for all received packets, including the address of the senders.
uint32_t m_satId
Satellite ID.
Private Member Functions
void EndTx ()
Notify a packet has finished being sent.
Address GetE2ESourceAddress (SatPhy::PacketContainer_t packets)
Get source address of packets.
void SendFromQueue ()
Send a packet from the queue.
Private Attributes
double m_extNoisePowerDensityDbwHz
Configured external noise power.
double m_fixedAmplificationGainDb
Fixed amplification gain used in RTN link at the satellite.
SatEnums::RegenerationMode_t m_forwardLinkRegenerationMode
Regeneration mode on forward link.
double m_imInterferenceCOverI
Intermodulation interference in linear.
double m_imInterferenceCOverIDb
Configured Intermodulation interference in dB.
bool m_isSending
Indicates if a packet is already being sent.
std::queue< std::tuple< Ptr< SatSignalParameters >, uint32_t, uint32_t > > m_queue
Simple FIFO queue to avoid collisions on TX in case of REGENERATION_PHY.
uint32_t m_queueSizeBytes
Size of FIFO queue in bytes.
uint32_t m_queueSizeMax
Maximum size of FIFO m_queue in bytes.
uint32_t m_queueSizePackets
Size of FIFO queue in packets.
SatEnums::RegenerationMode_t m_returnLinkRegenerationMode
Regeneration mode on return link.
Detailed Description
The SatOrbiterFeederPhy models the feeder link physical layer of the satellite node.
Definition at line 54 of file satellite-orbiter-feeder-phy.h.
Member Typedef Documentation
QueueSizeCallback
typedef void(* ns3::SatOrbiterFeederPhy::QueueSizeCallback) (uint32_t size, const Address &from)
Callback signature for QueueSizeBytes and QueueSizePackets trace source.
Parameters
size number of bytes or number of packets of queue
from The MAC source address of packets
Definition at line 113 of file satellite-orbiter-feeder-phy.h.
Constructor & Destructor Documentation
SatOrbiterFeederPhy() [1/2]
ns3::SatOrbiterFeederPhy::SatOrbiterFeederPhy (void)
Default constructor.
Definition at line 168 of file satellite-orbiter-feeder-phy.cc.
SatOrbiterFeederPhy() [2/2]
ns3::SatOrbiterFeederPhy::SatOrbiterFeederPhy (SatPhy::CreateParam_t & params, Ptr< SatLinkResults > linkResults, SatPhyRxCarrierConf::RxCarrierCreateParams_s parameters, Ptr< SatSuperframeConf > superFrameConf)
Definition at line 180 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatPhy::ConfigureRxCarriers(), ns3::SatUtils::DbToLinear(), ns3::SatEnums::FORWARD_FEEDER_CH, GetAdditionalInterference(), ns3::SatPhy::GetPhyTx(), ns3::SatPhy::GetRxNoiseTemperatureDbk(), m_extNoisePowerDensityDbwHz, m_forwardLinkRegenerationMode, m_imInterferenceCOverI, m_imInterferenceCOverIDb, m_isSending, m_queue, m_queueSizeBytes, m_queueSizePackets, m_returnLinkRegenerationMode, ns3::SatPhyRxCarrierConf::NORMAL, ns3::SatPhyTx::NORMAL, ns3::SatEnums::REGENERATION_PHY, ns3::SatEnums::TRANSPARENT, ns3::SatPhyRxCarrierConf::TRANSPARENT, and ns3::SatPhyTx::TRANSPARENT.
~SatOrbiterFeederPhy()
ns3::SatOrbiterFeederPhy::~SatOrbiterFeederPhy () virtual
Destructor for SatOrbiterFeederPhy.
Definition at line 242 of file satellite-orbiter-feeder-phy.cc.
Member Function Documentation
DoDispose()
void ns3::SatOrbiterFeederPhy::DoDispose (void) virtual
Dispose of this class instance.
Reimplemented from ns3::SatPhy.
Definition at line 248 of file satellite-orbiter-feeder-phy.cc.
DoInitialize()
void ns3::SatOrbiterFeederPhy::DoInitialize (void) virtual
Initialization of SatPhy.
Reimplemented from ns3::SatPhy.
Definition at line 255 of file satellite-orbiter-feeder-phy.cc.
EndTx()
void ns3::SatOrbiterFeederPhy::EndTx () private
Notify a packet has finished being sent.
Used only in REGENERATION_PHY mode.
Definition at line 384 of file satellite-orbiter-feeder-phy.cc.
References m_isSending, m_queue, and SendFromQueue().
Referenced by SendFromQueue().
GetAdditionalInterference()
double ns3::SatOrbiterFeederPhy::GetAdditionalInterference () virtual
Get additional interference, used to compute final SINR at RX.
Returns
Additional interference
Implements ns3::SatPhy.
Definition at line 492 of file satellite-orbiter-feeder-phy.cc.
References m_imInterferenceCOverI.
Referenced by SatOrbiterFeederPhy().
GetE2ESourceAddress()
Address ns3::SatOrbiterFeederPhy::GetE2ESourceAddress (SatPhy::PacketContainer_t packets) private
Get source address of packets.
packets The packets from where extract source
Returns
The source MAC address
Definition at line 512 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatAddressTag::GetSourceAddress(), and ns3::SatAddressTag::GetTypeId().
Referenced by SendFromQueue(), and SendPduWithParams().
GetInstanceTypeId()
TypeId ns3::SatOrbiterFeederPhy::GetInstanceTypeId (void) const
Definition at line 161 of file satellite-orbiter-feeder-phy.cc.
References GetTypeId().
GetSatLinkRxDir()
SatEnums::SatLinkDir_t ns3::SatOrbiterFeederPhy::GetSatLinkRxDir () protected virtual
Get the link RX direction.
Must be implemented by child clases.
Returns
The link RX direction
Reimplemented from ns3::SatPhy.
Definition at line 506 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatEnums::LD_FORWARD.
GetSatLinkTxDir()
SatEnums::SatLinkDir_t ns3::SatOrbiterFeederPhy::GetSatLinkTxDir () protected virtual
Get the link TX direction.
Must be implemented by child clases.
Returns
The link TX direction
Reimplemented from ns3::SatPhy.
Definition at line 500 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatEnums::LD_RETURN.
GetTypeId()
TypeId ns3::SatOrbiterFeederPhy::GetTypeId (void) static
inherited from Object
Definition at line 56 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatPhy::GetDefaultFading(), ns3::SatPhy::GetPhyRx(), ns3::SatPhy::GetPhyTx(), ns3::SatPhy::GetRxAntennaGainDb(), ns3::SatPhy::GetRxAntennaLossDb(), ns3::SatPhy::GetRxNoiseTemperatureDbk(), ns3::SatPhy::GetTxAntennaGainDb(), ns3::SatPhy::GetTxAntennaLossDb(), ns3::SatPhy::GetTxMaxPowerDbw(), ns3::SatPhy::GetTxOboLossDb(), ns3::SatPhy::GetTxOutputLossDb(), ns3::SatPhy::GetTxPointingLossDb(), m_extNoisePowerDensityDbwHz, m_fixedAmplificationGainDb, m_imInterferenceCOverIDb, m_queueSizeBytesTrace, m_queueSizeMax, m_queueSizePacketsTrace, ns3::SatPhy::SetDefaultFading(), ns3::SatPhy::SetPhyRx(), ns3::SatPhy::SetPhyTx(), ns3::SatPhy::SetRxAntennaGainDb(), ns3::SatPhy::SetRxAntennaLossDb(), ns3::SatPhy::SetRxNoiseTemperatureDbk(), ns3::SatPhy::SetTxAntennaGainDb(), ns3::SatPhy::SetTxAntennaLossDb(), ns3::SatPhy::SetTxMaxPowerDbw(), ns3::SatPhy::SetTxOboLossDb(), ns3::SatPhy::SetTxOutputLossDb(), and ns3::SatPhy::SetTxPointingLossDb().
Referenced by GetInstanceTypeId().
Receive()
void ns3::SatOrbiterFeederPhy::Receive (Ptr< SatSignalParameters > rxParams, bool phyError) virtual
Receives packets from lower layer.
Parameters
rxParams Packet reception parameters
phyError Boolean indicating whether the packet successfully received or not? Note, that this parameter is not used in the satellite, but exists since we are using a general interface defined in the parent class.
Reimplemented from ns3::SatPhy.
Definition at line 434 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatUtils::GetPacketInfo(), ns3::SatEnums::LD_FORWARD, ns3::SatEnums::LL_PHY, m_forwardLinkRegenerationMode, ns3::SatPhy::m_nodeInfo, ns3::SatPhy::m_packetTrace, ns3::SatPhy::m_rxCallback, ns3::SatPhy::ModcodTrace(), ns3::SatEnums::PACKET_DROP, ns3::SatEnums::PACKET_RECV, ns3::SatEnums::PACKET_TYPE_DEDICATED_ACCESS, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatEnums::REGENERATION_PHY, RxTraces(), ns3::SatUplinkInfoTag::SetBeamId(), ns3::SatUplinkInfoTag::SetSatId(), and ns3::SatEnums::TRANSPARENT.
RxTraces()
void ns3::SatOrbiterFeederPhy::RxTraces (SatPhy::PacketContainer_t packets) protected virtual
Invoke the Rx trace source for each received packet.
Parameters
packets Container of the pointers to the packets received.
Reimplemented from ns3::SatPhy.
Definition at line 394 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatAddressE2ETag::GetE2EDestAddress(), ns3::SatPhyLinkTimeTag::GetSenderLinkTimestamp(), ns3::SatPhy::m_isStatisticsTagsEnabled, ns3::SatPhy::m_lastLinkDelay, ns3::SatPhy::m_rxLinkDelayTrace, ns3::SatPhy::m_rxLinkJitterTrace, and ns3::SatPhy::m_rxTrace.
Referenced by Receive().
SendFromQueue()
void ns3::SatOrbiterFeederPhy::SendFromQueue () private
Send a packet from the queue.
Used only in REGENERATION_PHY mode.
Definition at line 351 of file satellite-orbiter-feeder-phy.cc.
References EndTx(), GetE2ESourceAddress(), ns3::SatUtils::GetPacketInfo(), ns3::SatEnums::LD_RETURN, ns3::SatEnums::LL_PHY, m_isSending, ns3::SatPhy::m_nodeInfo, ns3::SatPhy::m_packetTrace, ns3::SatPhy::m_phyTx, m_queue, m_queueSizeBytes, m_queueSizeBytesTrace, m_queueSizePackets, m_queueSizePacketsTrace, and ns3::SatEnums::PACKET_SENT.
Referenced by EndTx(), and SendPduWithParams().
SendPduWithParams()
void ns3::SatOrbiterFeederPhy::SendPduWithParams (Ptr< SatSignalParameters > rxParams) virtual
Send Pdu to the PHY tx module (for satellite switch packet forwarding)
Parameters
rxParams Transmission parameters
In return link, at the satellite, instead of using a constant EIRP (without gain), we are using a fixed amplifier gain amplifying the received signal. With this fixed gain, all bursts in a slot are amplified by the same amplification gain before being transmitted on the feeder link downlink. So, the tx power will be weak for the weak burst, and strong for the strong burst. This approach shall be used for: 1) RTN link only. 2) For all CRDSA, SA, and DA.
Reimplemented from ns3::SatPhy.
Definition at line 262 of file satellite-orbiter-feeder-phy.cc.
References ns3::SatUtils::DbToLinear(), GetE2ESourceAddress(), ns3::SatUtils::GetPacketInfo(), ns3::SatEnums::LD_RETURN, ns3::SatUtils::LinearToDb(), ns3::SatEnums::LL_PHY, ns3::SatPhy::m_eirpWoGainW, m_fixedAmplificationGainDb, m_isSending, ns3::SatPhy::m_nodeInfo, ns3::SatPhy::m_packetTrace, ns3::SatPhy::m_phyTx, m_queue, m_queueSizeBytes, m_queueSizeBytesTrace, m_queueSizeMax, m_queueSizePackets, m_queueSizePacketsTrace, m_returnLinkRegenerationMode, ns3::SatEnums::PACKET_DROP, ns3::SatEnums::PACKET_ENQUE, ns3::SatEnums::PACKET_SENT, ns3::SatEnums::REGENERATION_PHY, SendFromQueue(), ns3::SatPhy::SetTimeTag(), and ns3::SatEnums::TRANSPARENT.
Referenced by ns3::SatOrbiterHelper::AttachChannelsFeeder().
Member Data Documentation
m_extNoisePowerDensityDbwHz
double ns3::SatOrbiterFeederPhy::m_extNoisePowerDensityDbwHz private
Configured external noise power.
Definition at line 165 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), and GetTypeId().
m_fixedAmplificationGainDb
double ns3::SatOrbiterFeederPhy::m_fixedAmplificationGainDb private
Fixed amplification gain used in RTN link at the satellite.
Definition at line 180 of file satellite-orbiter-feeder-phy.h.
Referenced by GetTypeId(), and SendPduWithParams().
m_forwardLinkRegenerationMode
SatEnums::RegenerationMode_t ns3::SatOrbiterFeederPhy::m_forwardLinkRegenerationMode private
Regeneration mode on forward link.
Definition at line 185 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), and Receive().
m_imInterferenceCOverI
double ns3::SatOrbiterFeederPhy::m_imInterferenceCOverI private
Intermodulation interference in linear.
Definition at line 175 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), and GetAdditionalInterference().
m_imInterferenceCOverIDb
double ns3::SatOrbiterFeederPhy::m_imInterferenceCOverIDb private
Configured Intermodulation interference in dB.
Definition at line 170 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), and GetTypeId().
m_isSending
bool ns3::SatOrbiterFeederPhy::m_isSending private
Indicates if a packet is already being sent.
Definition at line 216 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), EndTx(), SendFromQueue(), and SendPduWithParams().
m_queue
std::queue<std::tuple<Ptr<SatSignalParameters>, uint32_t, uint32_t> > ns3::SatOrbiterFeederPhy::m_queue private
Simple FIFO queue to avoid collisions on TX in case of REGENERATION_PHY.
Second and third elements are respectively size in bytes and in packets.
Definition at line 196 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), EndTx(), SendFromQueue(), and SendPduWithParams().
m_queueSizeBytes
uint32_t ns3::SatOrbiterFeederPhy::m_queueSizeBytes private
Size of FIFO queue in bytes.
Definition at line 201 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), SendFromQueue(), and SendPduWithParams().
m_queueSizeBytesTrace
TracedCallback<uint32_t, const Address&> ns3::SatOrbiterFeederPhy::m_queueSizeBytesTrace protected
Traced callback to monitor RTN feeder queue size in bytes.
Definition at line 137 of file satellite-orbiter-feeder-phy.h.
Referenced by GetTypeId(), SendFromQueue(), and SendPduWithParams().
m_queueSizeMax
uint32_t ns3::SatOrbiterFeederPhy::m_queueSizeMax private
Maximum size of FIFO m_queue in bytes.
Definition at line 211 of file satellite-orbiter-feeder-phy.h.
Referenced by GetTypeId(), and SendPduWithParams().
m_queueSizePackets
uint32_t ns3::SatOrbiterFeederPhy::m_queueSizePackets private
Size of FIFO queue in packets.
Definition at line 206 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), SendFromQueue(), and SendPduWithParams().
m_queueSizePacketsTrace
TracedCallback<uint32_t, const Address&> ns3::SatOrbiterFeederPhy::m_queueSizePacketsTrace protected
Traced callback to monitor RTN feeder queue size in packets.
Definition at line 142 of file satellite-orbiter-feeder-phy.h.
Referenced by GetTypeId(), SendFromQueue(), and SendPduWithParams().
m_returnLinkRegenerationMode
SatEnums::RegenerationMode_t ns3::SatOrbiterFeederPhy::m_returnLinkRegenerationMode private
Regeneration mode on return link.
Definition at line 190 of file satellite-orbiter-feeder-phy.h.
Referenced by SatOrbiterFeederPhy(), and SendPduWithParams().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-orbiter-feeder-phy.h
/builds/sns3/satellite/satellite/model/satellite-orbiter-feeder-phy.cc