SNS3
ns3::SatStatsHelper Class Reference abstract
Satellite Statistics
Parent abstract class of all satellite statistics helpers.
#include "satellite-stats-helper.h"
Public Types
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Public Member Functions
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
virtual void UpdateAddressAndIdentifier (Ptr< Node > utNode)
Update the address and the proper identifier from the given UT node.
virtual void UpdateIdentifierOnProbes ()
Change identifier used on probes, when handovers occur.
Static Public Member Functions
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual void DoInstall ()=0
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
virtual void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
Static Protected Member Functions
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatOrbiterNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Protected Attributes
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it.
Private Attributes
IdentifierType_t m_identifierType
bool m_isInstalled
std::string m_name
OutputType_t m_outputType
Ptr< const SatHelper > m_satHelper
Detailed Description
Parent abstract class of all satellite statistics helpers.
A helper is responsible to locate source objects, create probes, collectors, and aggregators, and connect them together in a proper way to produce the required statistics.
The main inputs for the helper are a reference to a SatHelper instance, a name, an identifier type, and an output type. After all the necessary inputs have been set, the statistics can be started into action by invoking Install(). For example:
Ptr<SatHelper> satHelper = CreateObject<SatHelper> ();
satHelper->CreateScenario (SatHelper::SIMPLE);
// ... (snip) ...
Ptr<SatStatsFwdSinrHelper> fwdFinr
    = CreateObject<SatStatsFwdSinrHelper> (satHelper);
stat->SetName ("name");
stat->SetIdentifierType (SatStatsHelper::IDENTIFIER_GLOBAL);
stat->SetOutputType (SatStatsHelper::OUTPUT_SCALAR_FILE);
stat->Install ();
However, it's recommended to use the SatStatsHelperContainer class to automatically handle the above.
This parent abstract class hosts several protected methods which are intended to simplify the development of child classes. Some of these methods handle tasks related to DCF components, while some other handle tasks related to satellite topology.
See also
SatStatsHelperContainer
Definition at line 88 of file satellite-stats-helper.h.
Member Enumeration Documentation
IdentifierType_t
enum ns3::SatStatsHelper::IdentifierType_t
Possible categorization of statistics output.
Enumerator
IDENTIFIER_GLOBAL
IDENTIFIER_GW
IDENTIFIER_BEAM
IDENTIFIER_UT
IDENTIFIER_UT_USER
IDENTIFIER_SLICE
IDENTIFIER_GROUP
IDENTIFIER_SAT
IDENTIFIER_ISL
Definition at line 97 of file satellite-stats-helper.h.
OutputType_t
enum ns3::SatStatsHelper::OutputType_t
Possible types and formats of statistics output.
Enumerator
OUTPUT_NONE
OUTPUT_SCALAR_FILE
OUTPUT_SCATTER_FILE
OUTPUT_HISTOGRAM_FILE
OUTPUT_PDF_FILE
OUTPUT_CDF_FILE
OUTPUT_SCALAR_PLOT
OUTPUT_SCATTER_PLOT
OUTPUT_HISTOGRAM_PLOT
OUTPUT_PDF_PLOT
OUTPUT_CDF_PLOT
Definition at line 120 of file satellite-stats-helper.h.
Constructor & Destructor Documentation
SatStatsHelper()
ns3::SatStatsHelper::SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
Parameters
satHelper pointer to a SatHelper instance where information about the simulation topology will be taken.
Definition at line 125 of file satellite-stats-helper.cc.
~SatStatsHelper()
ns3::SatStatsHelper::~SatStatsHelper () virtual
/ Destructor.
Definition at line 135 of file satellite-stats-helper.cc.
Member Function Documentation
CreateAggregator()
Ptr< DataCollectionObject > ns3::SatStatsHelper::CreateAggregator (std::string aggregatorTypeId, std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue(), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue(), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue(), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue(), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue()) protected
Create the aggregator according to the output type.
Parameters
aggregatorTypeId the type of aggregator to be created.
n1 the name of the attribute to be set on the aggregator created.
v1 the value of the attribute to be set on the aggregator created.
n2 the name of the attribute to be set on the aggregator created.
v2 the value of the attribute to be set on the aggregator created.
n3 the name of the attribute to be set on the aggregator created.
v3 the value of the attribute to be set on the aggregator created.
n4 the name of the attribute to be set on the aggregator created.
v4 the value of the attribute to be set on the aggregator created.
n5 the name of the attribute to be set on the aggregator created.
v5 the value of the attribute to be set on the aggregator created.
Returns
a pointer to the created aggregator.
Definition at line 301 of file satellite-stats-helper.cc.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsBeamServiceTimeHelper::DoInstall(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), and ns3::SatStatsWindowLoadHelper::DoInstall().
CreateCollectorPerIdentifier()
uint32_t ns3::SatStatsHelper::CreateCollectorPerIdentifier (CollectorMap & collectorMap) const protected
Create one collector instance for each identifier in the simulation.
Parameters
collectorMap the CollectorMap where the collectors will be created.
Returns
number of collector instances created.
The identifier is determined by the currently active identifier type, as previously selected by SetIdentifierType() method or IdentifierType attribute. Then the method searches the reference SatHelper instance for such identifier. For each of the found identifiers, the method creates a collector instance for it, assigns the collector instance a meaningful name, and put the collector instance into the CollectorMap.
Definition at line 327 of file satellite-stats-helper.cc.
References GetGwId(), GetIdentifierType(), GetIdentifierTypeName(), GetSatId(), GetSatSatOrbiterNetDevice(), GetUtId(), GetUtUserId(), IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, IDENTIFIER_GW, IDENTIFIER_ISL, IDENTIFIER_SAT, IDENTIFIER_SLICE, IDENTIFIER_UT, IDENTIFIER_UT_USER, m_satHelper, ns3::SatConstVariables::MAX_BEAMS_PER_SATELLITE, and ns3::SatConstVariables::MAX_SATELLITES.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), and ns3::SatStatsThroughputHelper::DoInstall().
DoInstall()
virtual void ns3::SatStatsHelper::DoInstall () protected pure virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Implemented in ns3::SatStatsWindowLoadHelper, ns3::SatStatsWaveformUsageHelper, ns3::SatStatsThroughputHelper, ns3::SatStatsSignallingLoadHelper, ns3::SatStatsSatelliteQueueHelper, ns3::SatStatsResourcesGrantedHelper, ns3::SatStatsRbdcRequestHelper, ns3::SatStatsQueueHelper, ns3::SatStatsPltHelper, ns3::SatStatsPacketErrorHelper, ns3::SatStatsPacketDropRateHelper, ns3::SatStatsUserPacketCollisionHelper, ns3::SatStatsFeederPacketCollisionHelper, ns3::SatStatsMarsalaCorrelationHelper, ns3::SatStatsLinkSinrHelper, ns3::SatStatsLinkRxPowerHelper, ns3::SatStatsLinkModcodHelper, ns3::SatStatsLinkJitterHelper, ns3::SatStatsLinkDelayHelper, ns3::SatStatsJitterHelper, ns3::SatStatsFwdLinkSchedulerSymbolRateHelper, ns3::SatStatsFrameTypeUsageHelper, ns3::SatStatsFrameLoadHelper, ns3::SatStatsDelayHelper, ns3::SatStatsCompositeSinrHelper, ns3::SatStatsCarrierIdHelper, ns3::SatStatsCapacityRequestHelper, ns3::SatStatsBeamServiceTimeHelper, ns3::SatStatsBackloggedRequestHelper, and ns3::SatStatsAntennaGainHelper.
Referenced by Install().
GetDistributionHeading()
std::string ns3::SatStatsHelper::GetDistributionHeading (std::string dataLabel) const protected virtual
Parameters
dataLabel the short name of the main data of this statistics
Returns
a string to be printed as the first line of output, consisting of the given data label and the title of the distribution column
Definition at line 539 of file satellite-stats-helper.cc.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), and ns3::SatStatsWindowLoadHelper::DoInstall().
GetGwId()
uint32_t ns3::SatStatsHelper::GetGwId (Ptr< Node > gwNode) const protected
Parameters
gwNode
Returns
the ID previously assigned to the GW, or zero if the GW is not assigned to any ID.
Definition at line 606 of file satellite-stats-helper.cc.
References ns3::SatIdMapper::GetGwIdWithMac(), and ns3::SatIdMapper::GetGwMacWithNode().
Referenced by CreateCollectorPerIdentifier(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::GetCollector(), GetIdentifierForGw(), and ns3::SatStatsWaveformUsageHelper::WaveformUsageCallback().
GetGwSatNetDevice()
NetDeviceContainer ns3::SatStatsHelper::GetGwSatNetDevice (Ptr< Node > gwNode) static protected
Returns
Definition at line 1024 of file satellite-stats-helper.cc.
Referenced by ns3::SatStatsFwdQueueHelper::DoEnlistSource(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsRtnCompositeSinrHelper::DoInstallProbes(), ns3::SatStatsFwdDevDelayHelper::DoInstallProbes(), ns3::SatStatsFwdMacDelayHelper::DoInstallProbes(), ns3::SatStatsFwdPhyDelayHelper::DoInstallProbes(), ns3::SatStatsRtnDevDelayHelper::DoInstallProbes(), ns3::SatStatsRtnMacDelayHelper::DoInstallProbes(), ns3::SatStatsRtnPhyDelayHelper::DoInstallProbes(), ns3::SatStatsFwdDevJitterHelper::DoInstallProbes(), ns3::SatStatsFwdMacJitterHelper::DoInstallProbes(), ns3::SatStatsFwdPhyJitterHelper::DoInstallProbes(), ns3::SatStatsRtnDevJitterHelper::DoInstallProbes(), ns3::SatStatsRtnMacJitterHelper::DoInstallProbes(), ns3::SatStatsRtnPhyJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkSinrHelper::DoInstallProbes(), ns3::SatStatsFwdSignallingLoadHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederWindowLoadHelper::DoInstallProbes(), ns3::SatStatsPacketErrorHelper::InstallProbeOnGw(), and ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::InstallProbes().
GetIdentifierForBeam()
uint32_t ns3::SatStatsHelper::GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const protected
Parameters
beamId
Returns
Definition at line 901 of file satellite-stats-helper.cc.
References GetIdentifierTypeName(), IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GW, IDENTIFIER_SAT, m_identifierType, m_satHelper, and ns3::SatConstVariables::MAX_BEAMS_PER_SATELLITE.
Referenced by ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), and ns3::SatStatsWaveformUsageHelper::DoInstall().
GetIdentifierForGroup()
uint32_t ns3::SatStatsHelper::GetIdentifierForGroup (uint32_t groupId) const protected
Parameters
groupId
Returns
Definition at line 939 of file satellite-stats-helper.cc.
References GetIdentifierTypeName(), IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, and m_identifierType.
GetIdentifierForGw()
uint32_t ns3::SatStatsHelper::GetIdentifierForGw (Ptr< Node > gwNode) const protected
Parameters
gwNode
Returns
Definition at line 964 of file satellite-stats-helper.cc.
References GetGwId(), GetIdentifierTypeName(), IDENTIFIER_GLOBAL, IDENTIFIER_GW, and m_identifierType.
GetIdentifierForIsl()
uint32_t ns3::SatStatsHelper::GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const protected
Parameters
satNode
Returns
Definition at line 1004 of file satellite-stats-helper.cc.
References GetIdentifierTypeName(), GetSatId(), IDENTIFIER_GLOBAL, IDENTIFIER_ISL, m_identifierType, and ns3::SatConstVariables::MAX_SATELLITES.
Referenced by ns3::SatStatsPacketDropRateHelper::InstallProbes(), and ns3::SatStatsPacketDropRateHelper::PacketDropRateCallback().
GetIdentifierForSat()
uint32_t ns3::SatStatsHelper::GetIdentifierForSat (Ptr< Node > satNode) const protected
Parameters
satNode
Returns
Definition at line 984 of file satellite-stats-helper.cc.
References GetIdentifierTypeName(), GetSatId(), IDENTIFIER_GLOBAL, IDENTIFIER_SAT, and m_identifierType.
GetIdentifierForUt()
uint32_t ns3::SatStatsHelper::GetIdentifierForUt (Ptr< Node > utNode) const protected
Parameters
utNode
Returns
Definition at line 810 of file satellite-stats-helper.cc.
References ns3::SatIdMapper::GetBeamIdWithMac(), ns3::SatIdMapper::GetGroupIdWithMac(), GetIdentifierTypeName(), ns3::SatIdMapper::GetSatIdWithMac(), GetUtId(), ns3::SatIdMapper::GetUtMacWithNode(), IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, IDENTIFIER_GW, IDENTIFIER_SAT, IDENTIFIER_UT, m_identifierType, m_satHelper, and ns3::SatConstVariables::MAX_BEAMS_PER_SATELLITE.
Referenced by ns3::SatStatsFwdQueueHelper::DoEnlistSource(), ns3::SatStatsRtnQueueHelper::DoEnlistSource(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsFwdCompositeSinrHelper::DoInstallProbes(), ns3::SatStatsFwdDevDelayHelper::DoInstallProbes(), ns3::SatStatsFwdMacDelayHelper::DoInstallProbes(), ns3::SatStatsFwdPhyDelayHelper::DoInstallProbes(), ns3::SatStatsFwdDevJitterHelper::DoInstallProbes(), ns3::SatStatsFwdMacJitterHelper::DoInstallProbes(), ns3::SatStatsFwdPhyJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnSignallingLoadHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsResourcesGrantedHelper::InstallProbe(), ns3::SatStatsPacketErrorHelper::InstallProbeOnUt(), ns3::SatStatsAntennaGainHelper::InstallProbes(), ns3::SatStatsRbdcRequestHelper::InstallProbes(), SaveAddressAndIdentifier(), UpdateAddressAndIdentifier(), ns3::SatStatsFwdDevDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdMacDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdPhyDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserDevLinkDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserMacLinkDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserPhyLinkDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdAppPltHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserDevThroughputHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserMacThroughputHelper::UpdateIdentifierOnProbes(), and ns3::SatStatsFwdUserPhyThroughputHelper::UpdateIdentifierOnProbes().
GetIdentifierForUtUser()
uint32_t ns3::SatStatsHelper::GetIdentifierForUtUser (Ptr< Node > utUserNode) const protected
Parameters
utUserNode
Returns
Definition at line 665 of file satellite-stats-helper.cc.
References ns3::SatIdMapper::GetBeamIdWithMac(), ns3::SatIdMapper::GetGroupIdWithMac(), GetIdentifierTypeName(), ns3::SatIdMapper::GetSatIdWithMac(), GetUtId(), ns3::SatIdMapper::GetUtMacWithNode(), GetUtUserId(), IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, IDENTIFIER_GW, IDENTIFIER_SAT, IDENTIFIER_UT, IDENTIFIER_UT_USER, m_identifierType, m_satHelper, and ns3::SatConstVariables::MAX_BEAMS_PER_SATELLITE.
Referenced by ns3::SatStatsFwdAppDelayHelper::DoInstallProbes(), ns3::SatStatsFwdAppJitterHelper::DoInstallProbes(), ns3::SatStatsFwdAppPltHelper::DoInstallProbes(), ns3::SatStatsFwdAppThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnAppDelayHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsRtnAppJitterHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsRtnAppPltHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsRtnAppThroughputHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsFwdCompositeSinrHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdAppDelayHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdAppJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdDevJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdMacJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdPhyJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserDevLinkJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsFwdUserPhyLinkJitterHelper::UpdateIdentifierOnProbes(), ns3::SatStatsPacketErrorHelper::UpdateIdentifierOnProbes(), ns3::SatStatsResourcesGrantedHelper::UpdateIdentifierOnProbes(), ns3::SatStatsRtnSignallingLoadHelper::UpdateIdentifierOnProbes(), and ns3::SatStatsFwdAppThroughputHelper::UpdateIdentifierOnProbes().
GetIdentifierHeading()
std::string ns3::SatStatsHelper::GetIdentifierHeading (std::string dataLabel) const protected virtual
Parameters
dataLabel the short name of the main data of this statistics
Returns
a string to be printed as the first line of output, consisting of the identifier title and the given data label
Reimplemented in ns3::SatStatsWaveformUsageHelper, ns3::SatStatsFrameTypeUsageHelper, and ns3::SatStatsFrameLoadHelper.
Definition at line 494 of file satellite-stats-helper.cc.
References GetIdentifierType(), IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, IDENTIFIER_GW, IDENTIFIER_ISL, IDENTIFIER_SAT, IDENTIFIER_SLICE, IDENTIFIER_UT, and IDENTIFIER_UT_USER.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), and ns3::SatStatsWindowLoadHelper::DoInstall().
GetIdentifierType()
SatStatsHelper::IdentifierType_t ns3::SatStatsHelper::GetIdentifierType () const
Returns
the currently active categorization of statistics output.
Definition at line 260 of file satellite-stats-helper.cc.
References m_identifierType.
Referenced by CreateCollectorPerIdentifier(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsBeamServiceTimeHelper::DoInstall(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::GetCollector(), ns3::SatStatsFrameLoadHelper::GetIdentifierHeading(), ns3::SatStatsFrameTypeUsageHelper::GetIdentifierHeading(), GetIdentifierHeading(), ns3::SatStatsWaveformUsageHelper::GetIdentifierHeading(), GetTypeId(), ns3::SatStatsRbdcRequestHelper::InstallProbes(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::SymbolRateCallback(), and ns3::SatStatsWaveformUsageHelper::WaveformUsageCallback().
GetIdentifierTypeName()
std::string ns3::SatStatsHelper::GetIdentifierTypeName (SatStatsHelper::IdentifierType_t identifierType) static
Parameters
identifierType an arbitrary identifier type.
Returns
representation of the identifier type in string.
Definition at line 58 of file satellite-stats-helper.cc.
References IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, IDENTIFIER_GW, IDENTIFIER_ISL, IDENTIFIER_SAT, IDENTIFIER_SLICE, IDENTIFIER_UT, and IDENTIFIER_UT_USER.
Referenced by CreateCollectorPerIdentifier(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsBeamServiceTimeHelper::DoInstall(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::GetCollector(), GetIdentifierForBeam(), GetIdentifierForGroup(), GetIdentifierForGw(), GetIdentifierForIsl(), GetIdentifierForSat(), GetIdentifierForUt(), GetIdentifierForUtUser(), SetIdentifierType(), SetOutputType(), and ns3::SatStatsWaveformUsageHelper::WaveformUsageCallback().
GetName()
std::string ns3::SatStatsHelper::GetName () const
Returns
the name of this helper instance.
Definition at line 237 of file satellite-stats-helper.cc.
References m_name.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), ns3::SatStatsWindowLoadHelper::DoInstall(), GetOutputFileName(), and GetTypeId().
GetOutputFileName()
std::string ns3::SatStatsHelper::GetOutputFileName () const protected virtual
Compute the path and file name where statistics output should be written to.
Returns
path and file name (without extension)
Path is determined by the SatEnvVariables singleton class. The file name is determined by the name of this class instance.
Definition at line 488 of file satellite-stats-helper.cc.
References GetName(), and GetOutputPath().
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsBeamServiceTimeHelper::DoInstall(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), and ns3::SatStatsWindowLoadHelper::DoInstall().
GetOutputPath()
std::string ns3::SatStatsHelper::GetOutputPath () const protected virtual
Returns
the path where statistics output should be written to.
Path is determined by the SatEnvVariables singleton class.
Definition at line 482 of file satellite-stats-helper.cc.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), ns3::SatStatsWindowLoadHelper::DoInstall(), and GetOutputFileName().
GetOutputType()
SatStatsHelper::OutputType_t ns3::SatStatsHelper::GetOutputType () const
Returns
the currently active types and formats of statistics output.
Definition at line 283 of file satellite-stats-helper.cc.
References m_outputType.
Referenced by ns3::SatStatsAntennaGainHelper::AntennaGainCallback(), ns3::SatStatsCarrierIdHelper::CarrierIdRxCallback(), ns3::SatStatsPacketCollisionHelper::CollisionRxCallback(), ns3::SatStatsCompositeSinrHelper::ConnectProbeToCollector(), ns3::SatStatsDelayHelper::ConnectProbeToCollector(), ns3::SatStatsJitterHelper::ConnectProbeToCollector(), ns3::SatStatsLinkDelayHelper::ConnectProbeToCollector(), ns3::SatStatsLinkJitterHelper::ConnectProbeToCollector(), ns3::SatStatsLinkModcodHelper::ConnectProbeToCollector(), ns3::SatStatsLinkRxPowerHelper::ConnectProbeToCollector(), ns3::SatStatsLinkSinrHelper::ConnectProbeToCollector(), ns3::SatStatsPacketErrorHelper::ConnectProbeToCollector(), ns3::SatStatsPltHelper::ConnectProbeToCollector(), ns3::SatStatsSatelliteQueueHelper::ConnectProbeToCollector(), ns3::SatStatsMarsalaCorrelationHelper::CorrelationRxCallback(), ns3::SatStatsCompositeSinrHelper::DisconnectProbeFromCollector(), ns3::SatStatsDelayHelper::DisconnectProbeFromCollector(), ns3::SatStatsJitterHelper::DisconnectProbeFromCollector(), ns3::SatStatsLinkDelayHelper::DisconnectProbeFromCollector(), ns3::SatStatsLinkJitterHelper::DisconnectProbeFromCollector(), ns3::SatStatsPacketErrorHelper::DisconnectProbeFromCollector(), ns3::SatStatsPltHelper::DisconnectProbeFromCollector(), ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsBeamServiceTimeHelper::DoInstall(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), ns3::SatStatsWindowLoadHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::ErrorRxCallback(), GetTypeId(), ns3::SatStatsPacketDropRateHelper::PacketDropRateCallback(), ns3::SatStatsDelayHelper::PassSampleToCollector(), ns3::SatStatsLinkDelayHelper::PassSampleToCollector(), ns3::SatStatsJitterHelper::PassSampleToCollector(), ns3::SatStatsLinkJitterHelper::PassSampleToCollector(), ns3::SatStatsPltHelper::PassSampleToCollector(), ns3::SatStatsLinkRxPowerHelper::PassSampleToCollector(), ns3::SatStatsLinkSinrHelper::PassSampleToCollector(), ns3::SatStatsLinkModcodHelper::PassSampleToCollector(), ns3::SatStatsSatelliteQueueHelper::PassSampleToCollector(), ns3::SatStatsQueueHelper::PushToCollector(), ns3::SatStatsRbdcRequestHelper::RbdcRateCallback(), ns3::SatStatsRtnCompositeSinrHelper::SinrCallback(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::SymbolRateCallback(), ns3::SatStatsResourcesGrantedHelper::UpdateIdentifierOnProbes(), and ns3::SatStatsWindowLoadHelper::WindowLoadCallback().
GetOutputTypeName()
std::string ns3::SatStatsHelper::GetOutputTypeName (SatStatsHelper::OutputType_t outputType) static
Parameters
outputType an arbitrary output type.
Returns
representation of the output type in string.
Definition at line 90 of file satellite-stats-helper.cc.
References OUTPUT_CDF_FILE, OUTPUT_CDF_PLOT, OUTPUT_HISTOGRAM_FILE, OUTPUT_HISTOGRAM_PLOT, OUTPUT_NONE, OUTPUT_PDF_FILE, OUTPUT_PDF_PLOT, OUTPUT_SCALAR_FILE, OUTPUT_SCALAR_PLOT, OUTPUT_SCATTER_FILE, and OUTPUT_SCATTER_PLOT.
Referenced by ns3::SatStatsAntennaGainHelper::AntennaGainCallback(), ns3::SatStatsCarrierIdHelper::CarrierIdRxCallback(), ns3::SatStatsPacketCollisionHelper::CollisionRxCallback(), ns3::SatStatsCompositeSinrHelper::ConnectProbeToCollector(), ns3::SatStatsDelayHelper::ConnectProbeToCollector(), ns3::SatStatsJitterHelper::ConnectProbeToCollector(), ns3::SatStatsLinkDelayHelper::ConnectProbeToCollector(), ns3::SatStatsLinkJitterHelper::ConnectProbeToCollector(), ns3::SatStatsLinkModcodHelper::ConnectProbeToCollector(), ns3::SatStatsLinkRxPowerHelper::ConnectProbeToCollector(), ns3::SatStatsLinkSinrHelper::ConnectProbeToCollector(), ns3::SatStatsPacketErrorHelper::ConnectProbeToCollector(), ns3::SatStatsPltHelper::ConnectProbeToCollector(), ns3::SatStatsSatelliteQueueHelper::ConnectProbeToCollector(), ns3::SatStatsMarsalaCorrelationHelper::CorrelationRxCallback(), ns3::SatStatsCompositeSinrHelper::DisconnectProbeFromCollector(), ns3::SatStatsDelayHelper::DisconnectProbeFromCollector(), ns3::SatStatsJitterHelper::DisconnectProbeFromCollector(), ns3::SatStatsLinkDelayHelper::DisconnectProbeFromCollector(), ns3::SatStatsLinkJitterHelper::DisconnectProbeFromCollector(), ns3::SatStatsPacketErrorHelper::DisconnectProbeFromCollector(), ns3::SatStatsPltHelper::DisconnectProbeFromCollector(), ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsBeamServiceTimeHelper::DoInstall(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), ns3::SatStatsWindowLoadHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::ErrorRxCallback(), ns3::SatStatsPacketDropRateHelper::PacketDropRateCallback(), ns3::SatStatsDelayHelper::PassSampleToCollector(), ns3::SatStatsLinkDelayHelper::PassSampleToCollector(), ns3::SatStatsJitterHelper::PassSampleToCollector(), ns3::SatStatsLinkJitterHelper::PassSampleToCollector(), ns3::SatStatsPltHelper::PassSampleToCollector(), ns3::SatStatsLinkRxPowerHelper::PassSampleToCollector(), ns3::SatStatsLinkSinrHelper::PassSampleToCollector(), ns3::SatStatsLinkModcodHelper::PassSampleToCollector(), ns3::SatStatsSatelliteQueueHelper::PassSampleToCollector(), ns3::SatStatsQueueHelper::PushToCollector(), ns3::SatStatsRbdcRequestHelper::RbdcRateCallback(), SetOutputType(), ns3::SatStatsRtnCompositeSinrHelper::SinrCallback(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::SymbolRateCallback(), ns3::SatStatsResourcesGrantedHelper::UpdateIdentifierOnProbes(), and ns3::SatStatsWindowLoadHelper::WindowLoadCallback().
GetSatHelper()
Ptr< const SatHelper > ns3::SatStatsHelper::GetSatHelper () const
Returns
a pointer to the the SatHelper instance used as a reference by this helper instance.
Definition at line 295 of file satellite-stats-helper.cc.
References m_satHelper.
Referenced by ns3::SatStatsFwdQueueHelper::DoEnlistSource(), ns3::SatStatsBackloggedRequestHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::DoInstall(), ns3::SatStatsFrameTypeUsageHelper::DoInstall(), ns3::SatStatsWaveformUsageHelper::DoInstall(), ns3::SatStatsFrameLoadHelper::GetCollector(), and ns3::SatStatsWaveformUsageHelper::WaveformUsageCallback().
GetSatId()
uint32_t ns3::SatStatsHelper::GetSatId (Ptr< Node > satNode) const protected
Parameters
satNode
Returns
the ID previously assigned to the SAT, or zero if the SAT is not assigned to any ID.
Definition at line 635 of file satellite-stats-helper.cc.
References ns3::SatIdMapper::GetSatIdWithMac(), and ns3::SatIdMapper::GetSatMacWithNode().
Referenced by CreateCollectorPerIdentifier(), GetIdentifierForIsl(), and GetIdentifierForSat().
GetSatSatOrbiterNetDevice()
Ptr< NetDevice > ns3::SatStatsHelper::GetSatSatOrbiterNetDevice (Ptr< Node > satNode) static protected
Returns
Definition at line 1067 of file satellite-stats-helper.cc.
Referenced by CreateCollectorPerIdentifier(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsFwdPhyDelayHelper::DoInstallProbes(), ns3::SatStatsRtnPhyDelayHelper::DoInstallProbes(), ns3::SatStatsFwdPhyJitterHelper::DoInstallProbes(), ns3::SatStatsRtnPhyJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkSinrHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkSinrHelper::DoInstallProbes(), ns3::SatStatsRtnFeederQueuePacketsHelper::DoInstallProbes(), ns3::SatStatsRtnFeederQueueBytesHelper::DoInstallProbes(), ns3::SatStatsFwdUserQueuePacketsHelper::DoInstallProbes(), ns3::SatStatsFwdUserQueueBytesHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsPacketErrorHelper::InstallProbeOnSatFeeder(), ns3::SatStatsPacketErrorHelper::InstallProbeOnSatUser(), and ns3::SatStatsPacketDropRateHelper::InstallProbes().
GetTimeHeading()
std::string ns3::SatStatsHelper::GetTimeHeading (std::string dataLabel) const protected virtual
Parameters
dataLabel the short name of the main data of this statistics
Returns
a string to be printed as the first line of output, consisting of the title of the time column and the given data label
Definition at line 533 of file satellite-stats-helper.cc.
Referenced by ns3::SatStatsAntennaGainHelper::DoInstall(), ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsCompositeSinrHelper::DoInstall(), ns3::SatStatsDelayHelper::DoInstall(), ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall(), ns3::SatStatsJitterHelper::DoInstall(), ns3::SatStatsLinkDelayHelper::DoInstall(), ns3::SatStatsLinkJitterHelper::DoInstall(), ns3::SatStatsLinkModcodHelper::DoInstall(), ns3::SatStatsLinkRxPowerHelper::DoInstall(), ns3::SatStatsLinkSinrHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketDropRateHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsPltHelper::DoInstall(), ns3::SatStatsQueueHelper::DoInstall(), ns3::SatStatsRbdcRequestHelper::DoInstall(), ns3::SatStatsResourcesGrantedHelper::DoInstall(), ns3::SatStatsSatelliteQueueHelper::DoInstall(), ns3::SatStatsSignallingLoadHelper::DoInstall(), ns3::SatStatsThroughputHelper::DoInstall(), and ns3::SatStatsWindowLoadHelper::DoInstall().
GetTypeId()
TypeId ns3::SatStatsHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 141 of file satellite-stats-helper.cc.
References GetIdentifierType(), GetName(), GetOutputType(), IDENTIFIER_BEAM, IDENTIFIER_GLOBAL, IDENTIFIER_GROUP, IDENTIFIER_GW, IDENTIFIER_ISL, IDENTIFIER_SAT, IDENTIFIER_SLICE, IDENTIFIER_UT, IDENTIFIER_UT_USER, OUTPUT_CDF_FILE, OUTPUT_CDF_PLOT, OUTPUT_HISTOGRAM_FILE, OUTPUT_HISTOGRAM_PLOT, OUTPUT_NONE, OUTPUT_PDF_FILE, OUTPUT_PDF_PLOT, OUTPUT_SCALAR_FILE, OUTPUT_SCATTER_FILE, OUTPUT_SCATTER_PLOT, SetIdentifierType(), SetName(), and SetOutputType().
GetUtId()
uint32_t ns3::SatStatsHelper::GetUtId (Ptr< Node > utNode) const protected
Parameters
utNode
Returns
the ID previously assigned to the UT, or zero if the UT is not assigned to any ID.
Definition at line 577 of file satellite-stats-helper.cc.
References ns3::SatIdMapper::GetUtIdWithMac(), and ns3::SatIdMapper::GetUtMacWithNode().
Referenced by CreateCollectorPerIdentifier(), ns3::SatStatsFwdCompositeSinrHelper::DoInstallProbes(), ns3::SatStatsFwdDevDelayHelper::DoInstallProbes(), ns3::SatStatsFwdMacDelayHelper::DoInstallProbes(), ns3::SatStatsFwdPhyDelayHelper::DoInstallProbes(), ns3::SatStatsFwdDevJitterHelper::DoInstallProbes(), ns3::SatStatsFwdMacJitterHelper::DoInstallProbes(), ns3::SatStatsFwdPhyJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnSignallingLoadHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyThroughputHelper::DoInstallProbes(), GetIdentifierForUt(), GetIdentifierForUtUser(), ns3::SatStatsResourcesGrantedHelper::InstallProbe(), and ns3::SatStatsPacketErrorHelper::InstallProbeOnUt().
GetUtSatNetDevice()
Ptr< NetDevice > ns3::SatStatsHelper::GetUtSatNetDevice (Ptr< Node > utNode) static protected
Returns
Definition at line 1049 of file satellite-stats-helper.cc.
Referenced by ns3::SatStatsRtnQueueHelper::DoEnlistSource(), ns3::SatStatsCapacityRequestHelper::DoInstall(), ns3::SatStatsFwdCompositeSinrHelper::DoInstallProbes(), ns3::SatStatsFwdDevDelayHelper::DoInstallProbes(), ns3::SatStatsFwdMacDelayHelper::DoInstallProbes(), ns3::SatStatsFwdPhyDelayHelper::DoInstallProbes(), ns3::SatStatsRtnDevDelayHelper::DoInstallProbes(), ns3::SatStatsRtnMacDelayHelper::DoInstallProbes(), ns3::SatStatsRtnPhyDelayHelper::DoInstallProbes(), ns3::SatStatsFwdDevJitterHelper::DoInstallProbes(), ns3::SatStatsFwdMacJitterHelper::DoInstallProbes(), ns3::SatStatsFwdPhyJitterHelper::DoInstallProbes(), ns3::SatStatsRtnDevJitterHelper::DoInstallProbes(), ns3::SatStatsRtnMacJitterHelper::DoInstallProbes(), ns3::SatStatsRtnPhyJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkSinrHelper::DoInstallProbes(), ns3::SatStatsRtnSignallingLoadHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsResourcesGrantedHelper::InstallProbe(), ns3::SatStatsPacketErrorHelper::InstallProbeOnUt(), and ns3::SatStatsRbdcRequestHelper::InstallProbes().
GetUtUserId()
uint32_t ns3::SatStatsHelper::GetUtUserId (Ptr< Node > utUserNode) const protected
Parameters
utUserNode
Returns
the ID previously assigned to the UT user, or zero if the UT user is not assigned to any ID.
Definition at line 547 of file satellite-stats-helper.cc.
References ns3::SatIdMapper::GetUtUserIdWithMac(), and ns3::SatIdMapper::GetUtUserMacWithNode().
Referenced by CreateCollectorPerIdentifier(), ns3::SatStatsFwdAppDelayHelper::DoInstallProbes(), ns3::SatStatsFwdAppJitterHelper::DoInstallProbes(), ns3::SatStatsFwdAppPltHelper::DoInstallProbes(), ns3::SatStatsFwdAppThroughputHelper::DoInstallProbes(), and GetIdentifierForUtUser().
Install()
void ns3::SatStatsHelper::Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
Behaviour should be implemented by child class in DoInstall().
Definition at line 205 of file satellite-stats-helper.cc.
References DoInstall(), m_isInstalled, m_outputType, and OUTPUT_NONE.
IsInstalled()
bool ns3::SatStatsHelper::IsInstalled () const
Returns
true if Install() has been invoked, otherwise false.
Definition at line 289 of file satellite-stats-helper.cc.
References m_isInstalled.
SaveAddressAndIdentifier()
void ns3::SatStatsHelper::SaveAddressAndIdentifier (Ptr< Node > utNode) protected virtual
Save the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
The address of the given node will be saved in the m_identifierMap member variable.
Definition at line 1081 of file satellite-stats-helper.cc.
References GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
Referenced by ns3::SatStatsCarrierIdHelper::DoInstall(), ns3::SatStatsMarsalaCorrelationHelper::DoInstall(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), ns3::SatStatsUserPacketCollisionHelper::DoInstall(), ns3::SatStatsPacketErrorHelper::DoInstall(), ns3::SatStatsRtnCompositeSinrHelper::DoInstallProbes(), ns3::SatStatsRtnDevDelayHelper::DoInstallProbes(), ns3::SatStatsRtnMacDelayHelper::DoInstallProbes(), ns3::SatStatsRtnPhyDelayHelper::DoInstallProbes(), ns3::SatStatsRtnDevJitterHelper::DoInstallProbes(), ns3::SatStatsRtnMacJitterHelper::DoInstallProbes(), ns3::SatStatsRtnPhyJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkDelayHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkModcodHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkModcodHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkRxPowerHelper::DoInstallProbes(), ns3::SatStatsFwdFeederLinkSinrHelper::DoInstallProbes(), ns3::SatStatsFwdUserLinkSinrHelper::DoInstallProbes(), ns3::SatStatsRtnFeederLinkSinrHelper::DoInstallProbes(), ns3::SatStatsRtnUserLinkSinrHelper::DoInstallProbes(), ns3::SatStatsRtnFeederQueuePacketsHelper::DoInstallProbes(), ns3::SatStatsRtnFeederQueueBytesHelper::DoInstallProbes(), ns3::SatStatsFwdUserQueuePacketsHelper::DoInstallProbes(), ns3::SatStatsFwdUserQueueBytesHelper::DoInstallProbes(), ns3::SatStatsFwdSignallingLoadHelper::DoInstallProbes(), ns3::SatStatsFwdFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyThroughputHelper::DoInstallProbes(), and ns3::SatStatsRtnUserPhyThroughputHelper::DoInstallProbes().
SetIdentifierType()
void ns3::SatStatsHelper::SetIdentifierType (SatStatsHelper::IdentifierType_t identifierType)
Parameters
identifierType categorization of statistics output.
Warning
Does not have any effect if invoked after Install().
Definition at line 243 of file satellite-stats-helper.cc.
References GetIdentifierTypeName(), m_identifierType, and m_isInstalled.
Referenced by GetTypeId().
SetName()
void ns3::SatStatsHelper::SetName (std::string name)
Parameters
name string to be prepended on every output file name.
Definition at line 222 of file satellite-stats-helper.cc.
References m_name.
Referenced by GetTypeId().
SetOutputType()
void ns3::SatStatsHelper::SetOutputType (SatStatsHelper::OutputType_t outputType)
Parameters
outputType types and formats of statistics output.
Warning
Does not have any effect if invoked after Install().
Definition at line 266 of file satellite-stats-helper.cc.
References GetIdentifierTypeName(), GetOutputTypeName(), m_identifierType, m_isInstalled, and m_outputType.
Referenced by GetTypeId().
UpdateAddressAndIdentifier()
void ns3::SatStatsHelper::UpdateAddressAndIdentifier (Ptr< Node > utNode) virtual
Update the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
Used for UT handovers.
Definition at line 1101 of file satellite-stats-helper.cc.
References GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
UpdateIdentifierOnProbes()
void ns3::SatStatsHelper::UpdateIdentifierOnProbes () virtual
Change identifier used on probes, when handovers occur.
Default implementation does nothing, and only classes using probes must have a custom implementation
Reimplemented in ns3::SatStatsFwdUserPhyThroughputHelper, ns3::SatStatsFwdUserMacThroughputHelper, ns3::SatStatsFwdUserDevThroughputHelper, ns3::SatStatsFwdAppThroughputHelper, ns3::SatStatsRtnSignallingLoadHelper, ns3::SatStatsResourcesGrantedHelper, ns3::SatStatsFwdAppPltHelper, ns3::SatStatsPacketErrorHelper, ns3::SatStatsFwdUserPhyLinkJitterHelper, ns3::SatStatsFwdUserMacLinkJitterHelper, ns3::SatStatsFwdUserDevLinkJitterHelper, ns3::SatStatsFwdUserPhyLinkDelayHelper, ns3::SatStatsFwdUserMacLinkDelayHelper, ns3::SatStatsFwdUserDevLinkDelayHelper, ns3::SatStatsFwdPhyJitterHelper, ns3::SatStatsFwdMacJitterHelper, ns3::SatStatsFwdDevJitterHelper, ns3::SatStatsFwdAppJitterHelper, ns3::SatStatsFwdPhyDelayHelper, ns3::SatStatsFwdMacDelayHelper, ns3::SatStatsFwdDevDelayHelper, ns3::SatStatsFwdAppDelayHelper, and ns3::SatStatsFwdCompositeSinrHelper.
Definition at line 1121 of file satellite-stats-helper.cc.
Member Data Documentation
m_identifierMap
std::map<const Address, uint32_t> ns3::SatStatsHelper::m_identifierMap protected
Map of address and the identifier associated with it.
Definition at line 422 of file satellite-stats-helper.h.
Referenced by ns3::SatStatsCarrierIdHelper::CarrierIdRxCallback(), ns3::SatStatsPacketCollisionHelper::CollisionRxCallback(), ns3::SatStatsMarsalaCorrelationHelper::CorrelationRxCallback(), ns3::SatStatsPacketErrorHelper::ErrorRxCallback(), ns3::SatStatsRtnAppDelayHelper::Ipv4Callback(), ns3::SatStatsRtnAppJitterHelper::Ipv4Callback(), ns3::SatStatsRtnAppPltHelper::Ipv4Callback(), ns3::SatStatsRtnAppThroughputHelper::Ipv4Callback(), ns3::SatStatsSatelliteQueueHelper::QueueSizeCallback(), ns3::SatStatsThroughputHelper::RxCallback(), ns3::SatStatsDelayHelper::RxDelayCallback(), ns3::SatStatsJitterHelper::RxJitterCallback(), ns3::SatStatsLinkJitterHelper::RxLinkJitterCallback(), ns3::SatStatsLinkModcodHelper::RxLinkModcodCallback(), ns3::SatStatsPltHelper::RxPltCallback(), ns3::SatStatsLinkRxPowerHelper::RxPowerCallback(), SaveAddressAndIdentifier(), ns3::SatStatsRtnAppDelayHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsRtnAppJitterHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsRtnAppPltHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsRtnAppThroughputHelper::SaveIpv4AddressAndIdentifier(), ns3::SatStatsSignallingLoadHelper::SignallingTxCallback(), ns3::SatStatsLinkSinrHelper::SinrCallback(), ns3::SatStatsRtnCompositeSinrHelper::SinrCallback(), and UpdateAddressAndIdentifier().
m_identifierType
IdentifierType_t ns3::SatStatsHelper::m_identifierType private
Definition at line 426 of file satellite-stats-helper.h.
Referenced by GetIdentifierForBeam(), GetIdentifierForGroup(), GetIdentifierForGw(), GetIdentifierForIsl(), GetIdentifierForSat(), GetIdentifierForUt(), GetIdentifierForUtUser(), GetIdentifierType(), SetIdentifierType(), and SetOutputType().
m_isInstalled
bool ns3::SatStatsHelper::m_isInstalled private
Definition at line 428 of file satellite-stats-helper.h.
Referenced by Install(), IsInstalled(), SetIdentifierType(), and SetOutputType().
m_name
std::string ns3::SatStatsHelper::m_name private
Definition at line 425 of file satellite-stats-helper.h.
Referenced by GetName(), and SetName().
m_outputType
OutputType_t ns3::SatStatsHelper::m_outputType private
Definition at line 427 of file satellite-stats-helper.h.
Referenced by GetOutputType(), Install(), and SetOutputType().
m_satHelper
Ptr<const SatHelper> ns3::SatStatsHelper::m_satHelper private
Definition at line 429 of file satellite-stats-helper.h.
Referenced by CreateCollectorPerIdentifier(), GetIdentifierForBeam(), GetIdentifierForUt(), GetIdentifierForUtUser(), and GetSatHelper().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-helper.cc