SNS3
ns3::SatOrbiterNetDeviceDvb Class Reference
SatOrbiterNetDeviceDvb to be utilized in geostationary satellite.
#include "satellite-orbiter-net-device-dvb.h"
Public Member Functions
SatOrbiterNetDeviceDvb ()
Default constructor.
virtual void ConnectUt (Mac48Address utAddress, uint32_t beamId)
Connect a UT to this satellite.
virtual void DisconnectUt (Mac48Address utAddress, uint32_t beamId)
Disconnect a UT to this satellite.
void ReceiveFromIsl (Ptr< Packet > packet, Mac48Address destination)
Receive a packet from ISL.
void ReceivePacketFeeder (Ptr< Packet > packet, const Address &feederAddress)
Receive the packet from the lower layers, in network regeneration on forward link.
void ReceivePacketUser (Ptr< Packet > packet, const Address &userAddress)
Receive the packet from the lower layers, in network regeneration on return link.
virtual bool SendControlMsgToFeeder (Ptr< SatControlMessage > msg, const Address &dest, Ptr< SatSignalParameters > rxParams)
Send a control packet on the feeder link.
Public Member Functions inherited from ns3::SatOrbiterNetDevice
SatOrbiterNetDevice ()
Default constructor.
void AddFeederMac (Ptr< SatMac > mac, Ptr< SatMac > macUsed, uint32_t beamId)
Add the Feeder MAC object for the beam.
void AddFeederPair (uint32_t beamId, Mac48Address satelliteFeederAddress)
Add an entry in the database to get satellite feeder address from beam ID.
void AddFeederPhy (Ptr< SatPhy > phy, uint32_t beamId)
Add the Feeder Phy object for the beam.
void AddIslsNetDevice (Ptr< PointToPointIslNetDevice > islNetDevices)
Add a ISL Net Device to this satellite.
virtual void AddLinkChangeCallback (Callback< void > callback)
void AddUserMac (Ptr< SatMac > mac, uint32_t beamId)
Add the User MAC object for the beam.
void AddUserPair (uint32_t beamId, Mac48Address satelliteUserAddress)
Add an entry in the database to get satellite user address from beam ID.
void AddUserPhy (Ptr< SatPhy > phy, uint32_t beamId)
Add the User Phy object for the beam.
void ConnectGw (Mac48Address gwAddress, uint32_t beamId)
Connect a GW to this satellite.
void DisconnectGw (Mac48Address gwAddress, uint32_t beamId)
Disconnect a GW to this satellite.
virtual Address GetAddress (void) const
std::map< uint32_t, Ptr< SatMac > > GetAllFeederMac ()
Get all Feeder MAC objects attached to this satellite.
Ptr< SatIslArbiter > GetArbiter ()
Get the arbiter for ISL routing.
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
std::map< uint32_t, Ptr< SatMac > > GetFeederMac ()
Get all Feeder MAC objects attached to this satellite that are in use.
Ptr< SatMac > GetFeederMac (uint32_t beamId)
Get the Feeder MAC object for the beam.
std::map< uint32_t, Ptr< SatPhy > > GetFeederPhy ()
Get all Feeder Phy objects attached to this satellite.
Ptr< SatPhy > GetFeederPhy (uint32_t beamId)
Get the Feeder Phy object for the beam.
std::set< Mac48Address > GetGwConnected ()
The the list of MAC GW connected to this satellite.
virtual uint32_t GetIfIndex (void) const
std::vector< Ptr< PointToPointIslNetDevice > > GetIslsNetDevices ()
Get all the ISL Net devices.
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
virtual Address GetMulticast (Ipv6Address addr) const
virtual Ptr< Node > GetNode (void) const
Mac48Address GetSatelliteFeederAddress (uint32_t beamId)
Get satellite feeder entry from associated beam ID.
Mac48Address GetSatelliteUserAddress (uint32_t beamId)
Get satellite user entry from associated beam ID.
std::map< uint32_t, Ptr< SatMac > > GetUserMac ()
Get all User MAC objects attached to this satellite.
Ptr< SatMac > GetUserMac (uint32_t beamId)
Get the User MAC object for the beam.
std::map< uint32_t, Ptr< SatPhy > > GetUserPhy ()
Get all User Phy objects attached to this satellite.
Ptr< SatPhy > GetUserPhy (uint32_t beamId)
Get the User Phy object for the beam.
std::set< Mac48Address > GetUtConnected ()
The the list of UT MAC connected to this satellite.
virtual bool IsBridge (void) const
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
virtual bool NeedsArp (void) const
void ReceiveFeeder (SatPhy::PacketContainer_t packets, Ptr< SatSignalParameters > rxParams)
Receive the packet from the lower layers.
void ReceiveUser (SatPhy::PacketContainer_t packets, Ptr< SatSignalParameters > rxParams)
Receive the packet from the lower layers.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
void SendToIsl (Ptr< Packet > packet, Mac48Address destination)
Send a packet to ISL.
virtual void SetAddress (Address address)
void SetArbiter (Ptr< SatIslArbiter > arbiter)
Set the arbiter for ISL routing.
void SetForwardLinkRegenerationMode (SatEnums::RegenerationMode_t forwardLinkRegenerationMode)
Set the forward link regeneration mode.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
void SetNodeId (uint32_t nodeId)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the SatOrbiterNetDevice.
void SetReturnLinkRegenerationMode (SatEnums::RegenerationMode_t returnLinkRegenerationMode)
Set the return link regeneration mode.
virtual bool SupportsSendFrom (void) const
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SatOrbiterNetDevice
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::SatOrbiterNetDevice
virtual void DoDispose (void)
Dispose of this class instance.
Address GetRxUtAddress (Ptr< Packet > packet, SatEnums::SatLinkDir_t ld)
Get UT MAC address associated to this packet.
Protected Attributes inherited from ns3::SatOrbiterNetDevice
Mac48Address m_address
std::map< uint32_t, Mac48Address > m_addressMapFeeder
std::map< uint32_t, Mac48Address > m_addressMapUser
std::map< uint32_t, Ptr< SatMac > > m_allFeederMac
Ptr< SatIslArbiter > m_arbiter
Arbiter used to route on ISLs.
std::set< uint32_t > m_broadcastReceived
Keep a count of all incoming broadcast data to avoid handling them several times.
std::map< uint32_t, Ptr< SatMac > > m_feederMac
std::map< uint32_t, Ptr< SatPhy > > m_feederPhy
SatEnums::RegenerationMode_t m_forwardLinkRegenerationMode
std::map< Mac48Address, uint32_t > m_gwConnected
Set containing all connected GWs.
uint32_t m_ifIndex
std::vector< Ptr< PointToPointIslNetDevice > > m_islNetDevices
List of ISLs starting from this node.
bool m_isStatisticsTagsEnabled
std::map< Mac48Address, Time > m_lastDelays
uint16_t m_mtu
Ptr< Node > m_node
uint32_t m_nodeId
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
NetDevice::PromiscReceiveCallback m_promiscCallback
Ptr< ErrorModel > m_receiveErrorModel
SatEnums::RegenerationMode_t m_returnLinkRegenerationMode
NetDevice::ReceiveCallback m_rxCallback
TracedCallback< const Time &, const Address & > m_rxFeederLinkDelayTrace
Traced callback for all received packets, including feeder link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxFeederLinkJitterTrace
Traced callback for all received packets, including feeder link jitter information and the address of the senders.
TracedCallback< Ptr< const Packet >, const Address & > m_rxFeederTrace
Traced callback for all received packets on feeder, including the address of the senders.
TracedCallback< const Time &, const Address & > m_rxUserLinkDelayTrace
Traced callback for all received packets, including user link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxUserLinkJitterTrace
Traced callback for all received packets, including user link jitter information and the address of the senders.
TracedCallback< Ptr< const Packet >, const Address & > m_rxUserTrace
Traced callback for all received packets on user, including the address of the senders.
TracedCallback< Ptr< const Packet >, const Address & > m_signallingTxTrace
Traced callback for all signalling (control message) packets sent, including the destination address.
TracedCallback< Ptr< const Packet > > m_txTrace
Traced callback for all packets received to be transmitted.
std::map< uint32_t, Ptr< SatMac > > m_userMac
std::map< uint32_t, Ptr< SatPhy > > m_userPhy
std::map< Mac48Address, uint32_t > m_utConnected
Set containing all connected UTs.
Detailed Description
SatOrbiterNetDeviceDvb to be utilized in geostationary satellite.
SatOrbiterNetDeviceDvb holds a set of phy layers towards user and feeder links; one pair of phy layers for each spot-beam. The SatNetDevice implements a simple switching between all user and feeder links modeling transparent payload.
Definition at line 54 of file satellite-orbiter-net-device-dvb.h.
Constructor & Destructor Documentation
SatOrbiterNetDeviceDvb()
ns3::SatOrbiterNetDeviceDvb::SatOrbiterNetDeviceDvb ()
Default constructor.
Definition at line 73 of file satellite-orbiter-net-device-dvb.cc.
Member Function Documentation
ConnectUt()
void ns3::SatOrbiterNetDeviceDvb::ConnectUt (Mac48Address utAddress, uint32_t beamId) virtual
Connect a UT to this satellite.
Parameters
utAddress MAC address of the UT to connect
beamId beam used by satellite to reach this UT
Implements ns3::SatOrbiterNetDevice.
Definition at line 369 of file satellite-orbiter-net-device-dvb.cc.
References ns3::SatOrbiterNetDevice::GetUserMac(), ns3::SatOrbiterNetDevice::m_nodeId, ns3::SatOrbiterNetDevice::m_userMac, and ns3::SatOrbiterNetDevice::m_utConnected.
DisconnectUt()
void ns3::SatOrbiterNetDeviceDvb::DisconnectUt (Mac48Address utAddress, uint32_t beamId) virtual
Disconnect a UT to this satellite.
Parameters
utAddress MAC address of the UT to disconnect
beamId beam used by satellite to reach this UT
Implements ns3::SatOrbiterNetDevice.
Definition at line 390 of file satellite-orbiter-net-device-dvb.cc.
References ns3::SatOrbiterNetDevice::GetUserMac(), ns3::SatOrbiterNetDevice::m_userMac, and ns3::SatOrbiterNetDevice::m_utConnected.
GetTypeId()
TypeId ns3::SatOrbiterNetDeviceDvb::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 65 of file satellite-orbiter-net-device-dvb.cc.
ReceiveFromIsl()
void ns3::SatOrbiterNetDeviceDvb::ReceiveFromIsl (Ptr< Packet > packet, Mac48Address destination) virtual
Receive a packet from ISL.
Parameters
packet The packet to send
destination The MAC address of ground station that will receive the packet
Implements ns3::SatOrbiterNetDevice.
Definition at line 233 of file satellite-orbiter-net-device-dvb.cc.
References ns3::SatUplinkInfoTag::GetBeamId(), ns3::SatOrbiterNetDevice::m_broadcastReceived, ns3::SatOrbiterNetDevice::m_feederMac, ns3::SatOrbiterNetDevice::m_gwConnected, ns3::SatOrbiterNetDevice::m_islNetDevices, ns3::SatOrbiterNetDevice::m_isStatisticsTagsEnabled, ns3::SatOrbiterNetDevice::m_userMac, ns3::SatOrbiterNetDevice::m_utConnected, and ns3::SatOrbiterNetDevice::SendToIsl().
ReceivePacketFeeder()
void ns3::SatOrbiterNetDeviceDvb::ReceivePacketFeeder (Ptr< Packet > packet, const Address & feederAddress) virtual
Receive the packet from the lower layers, in network regeneration on forward link.
Parameters
packet Packet received
feederAddress MAC address of feeder that received this packet
Implements ns3::SatOrbiterNetDevice.
Definition at line 155 of file satellite-orbiter-net-device-dvb.cc.
References ns3::SatUplinkInfoTag::GetBeamId(), ns3::SatGroundStationAddressTag::GetGroundStationAddress(), ns3::SatUtils::GetPacketInfo(), ns3::SatOrbiterNetDevice::GetRxUtAddress(), ns3::SatDevLinkTimeTag::GetSenderTimestamp(), ns3::SatEnums::LD_FORWARD, ns3::SatEnums::LL_ND, ns3::SatOrbiterNetDevice::m_broadcastReceived, ns3::SatOrbiterNetDevice::m_islNetDevices, ns3::SatOrbiterNetDevice::m_isStatisticsTagsEnabled, ns3::SatOrbiterNetDevice::m_lastDelays, ns3::SatOrbiterNetDevice::m_nodeId, ns3::SatOrbiterNetDevice::m_packetTrace, ns3::SatOrbiterNetDevice::m_rxFeederLinkDelayTrace, ns3::SatOrbiterNetDevice::m_rxFeederLinkJitterTrace, ns3::SatOrbiterNetDevice::m_rxFeederTrace, ns3::SatOrbiterNetDevice::m_userMac, ns3::SatOrbiterNetDevice::m_utConnected, ns3::SatEnums::NT_SAT, ns3::SatEnums::PACKET_RECV, and ns3::SatOrbiterNetDevice::SendToIsl().
ReceivePacketUser()
void ns3::SatOrbiterNetDeviceDvb::ReceivePacketUser (Ptr< Packet > packet, const Address & userAddress) virtual
Receive the packet from the lower layers, in network regeneration on return link.
Parameters
packet Packet received
userAddress MAC address of user that received this packet
Implements ns3::SatOrbiterNetDevice.
Definition at line 80 of file satellite-orbiter-net-device-dvb.cc.
References ns3::SatUplinkInfoTag::GetBeamId(), ns3::SatGroundStationAddressTag::GetGroundStationAddress(), ns3::SatUtils::GetPacketInfo(), ns3::SatOrbiterNetDevice::GetRxUtAddress(), ns3::SatDevLinkTimeTag::GetSenderTimestamp(), ns3::SatEnums::LD_RETURN, ns3::SatEnums::LL_ND, ns3::SatOrbiterNetDevice::m_feederMac, ns3::SatOrbiterNetDevice::m_gwConnected, ns3::SatOrbiterNetDevice::m_islNetDevices, ns3::SatOrbiterNetDevice::m_isStatisticsTagsEnabled, ns3::SatOrbiterNetDevice::m_lastDelays, ns3::SatOrbiterNetDevice::m_nodeId, ns3::SatOrbiterNetDevice::m_packetTrace, ns3::SatOrbiterNetDevice::m_rxUserLinkDelayTrace, ns3::SatOrbiterNetDevice::m_rxUserLinkJitterTrace, ns3::SatOrbiterNetDevice::m_rxUserTrace, ns3::SatEnums::NT_SAT, ns3::SatEnums::PACKET_RECV, and ns3::SatOrbiterNetDevice::SendToIsl().
SendControlMsgToFeeder()
bool ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder (Ptr< SatControlMessage > msg, const Address & dest, Ptr< SatSignalParameters > rxParams) virtual
Send a control packet on the feeder link.
Parameters
msg The control message to send
dest The MAC destination
rxParams Strucutre storing additional parameters
Returns
True if success
Implements ns3::SatOrbiterNetDevice.
Definition at line 297 of file satellite-orbiter-net-device-dvb.cc.
References ns3::SatOrbiterNetDevice::m_address, ns3::SatOrbiterNetDevice::m_feederMac, ns3::SatOrbiterNetDevice::m_feederPhy, ns3::SatOrbiterNetDevice::m_isStatisticsTagsEnabled, ns3::SatOrbiterNetDevice::m_returnLinkRegenerationMode, ns3::SatEnums::REGENERATION_LINK, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatEnums::REGENERATION_PHY, ns3::SatUplinkInfoTag::SetBeamId(), ns3::SatMacTag::SetDestAddress(), ns3::SatAddressE2ETag::SetE2EDestAddress(), ns3::SatAddressE2ETag::SetE2ESourceAddress(), ns3::SatControlMsgTag::SetMsgId(), ns3::SatControlMsgTag::SetMsgType(), ns3::SatUplinkInfoTag::SetSatId(), ns3::SatUplinkInfoTag::SetSinr(), ns3::SatMacTag::SetSourceAddress(), and ns3::SatEnums::TRANSPARENT.
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-orbiter-net-device-dvb.h
/builds/sns3/satellite/satellite/model/satellite-orbiter-net-device-dvb.cc