SNS3
ns3::SatControlMsgTag Class Reference
This class implements a tag that is used to identify control messages (packages).
#include "satellite-control-message.h"
Public Types
enum SatControlMsgType_t {
SAT_NON_CTRL_MSG , SAT_TBTP_CTRL_MSG , SAT_CR_CTRL_MSG , SAT_RA_CTRL_MSG ,
SAT_ARQ_ACK , SAT_CN0_REPORT , SAT_TIMU_CTRL_MSG , SAT_HR_CTRL_MSG ,
SAT_SLICE_CTRL_MSG , SAT_LOGON_CTRL_MSG , SAT_LOGON_RESPONSE_CTRL_MSG , SAT_LOGOFF_CTRL_MSG ,
SAT_NCR_CTRL_MSG , SAT_CMT_CTRL_MSG
}
Definition for different types of control messages.
Public Member Functions
SatControlMsgTag ()
Constructor for SatControlMsgTag.
~SatControlMsgTag ()
Destructor for SatControlMsgTag.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of methods.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
virtual uint32_t GetMsgId () const
Get message type specific identifier.
SatControlMsgType_t GetMsgType (void) const
Get type of the control message.
virtual uint32_t GetSerializedSize (void) const
Get serialized size of methods.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of methods.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of methods.
virtual void SetMsgId (uint32_t msgId)
Set message type specific identifier.
void SetMsgType (SatControlMsgType_t type)
Set type of the control message.
Static Public Member Functions
static TypeId GetTypeId (void)
methods derived from base classes
Private Attributes
uint32_t m_msgId
SatControlMsgType_t m_msgType
Detailed Description
This class implements a tag that is used to identify control messages (packages).
Definition at line 51 of file satellite-control-message.h.
Member Enumeration Documentation
SatControlMsgType_t
enum ns3::SatControlMsgTag::SatControlMsgType_t
Definition for different types of control messages.
Enumerator
SAT_NON_CTRL_MSG
SAT_NON_CTRL_MSG.
SAT_TBTP_CTRL_MSG
SAT_TBTP_CTRL_MSG.
SAT_CR_CTRL_MSG
SAT_CR_CTRL_MSG.
SAT_RA_CTRL_MSG
SAT_RA_CTRL_MSG.
SAT_ARQ_ACK
SAT_ARQ_ACK.
SAT_CN0_REPORT
SAT_CN0_REPORT.
SAT_TIMU_CTRL_MSG
SAT_TIMU_CTRL_MSG.
SAT_HR_CTRL_MSG
SAT_HR_CTRL_MSG.
SAT_SLICE_CTRL_MSG
SAT_SLICE_CTRL_MSG.
SAT_LOGON_CTRL_MSG
SAT_LOGON_CTRL_MSG.
SAT_LOGON_RESPONSE_CTRL_MSG
SAT_LOGON_RESPONSE_CTRL_MSG.
SAT_LOGOFF_CTRL_MSG
SAT_LOGOFF CTRL_MSG.
SAT_NCR_CTRL_MSG
SAT_NCR_CTRL_MSG.
SAT_CMT_CTRL_MSG
SAT_CMT_CTRL_MSG.
Definition at line 57 of file satellite-control-message.h.
Constructor & Destructor Documentation
SatControlMsgTag()
ns3::SatControlMsgTag::SatControlMsgTag ()
Constructor for SatControlMsgTag.
Definition at line 44 of file satellite-control-message.cc.
~SatControlMsgTag()
ns3::SatControlMsgTag::~SatControlMsgTag ()
Destructor for SatControlMsgTag.
Definition at line 51 of file satellite-control-message.cc.
Member Function Documentation
Deserialize()
void ns3::SatControlMsgTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of methods.
Parameters
i Buffer from which the information is deserialized
Definition at line 103 of file satellite-control-message.cc.
References m_msgId, and m_msgType.
GetInstanceTypeId()
TypeId ns3::SatControlMsgTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 65 of file satellite-control-message.cc.
References GetTypeId().
GetMsgId()
uint32_t ns3::SatControlMsgTag::GetMsgId () const virtual
Get message type specific identifier.
Returns
Message type specific identifier.
Definition at line 125 of file satellite-control-message.cc.
References m_msgId.
Referenced by ns3::SatLlc::ReceiveHigherLayerPdu(), ns3::SatOrbiterLlc::ReceiveHigherLayerPdu(), ns3::SatOrbiterFeederMac::ReceiveSignalingPacket(), ns3::SatOrbiterUserMac::ReceiveSignalingPacket(), ns3::SatUtMac::ReceiveSignalingPacket(), ns3::SatGwMac::ReceiveSignalingPacket(), and ns3::SatMac::SendPacket().
GetMsgType()
SatControlMsgTag::SatControlMsgType_t ns3::SatControlMsgTag::GetMsgType (void) const
Get type of the control message.
Returns
The type of the control message
Definition at line 80 of file satellite-control-message.cc.
References m_msgType.
Referenced by ns3::SatQueue::Enqueue(), ns3::SatUtMac::ExtractPacketsToSchedule(), ns3::SatOrbiterFeederMac::Receive(), ns3::SatOrbiterUserMac::Receive(), ns3::SatGwMac::Receive(), ns3::SatUtMac::Receive(), ns3::SatLlc::ReceiveHigherLayerPdu(), ns3::SatOrbiterLlc::ReceiveHigherLayerPdu(), ns3::SatOrbiterFeederMac::ReceiveSignalingPacket(), ns3::SatOrbiterUserMac::ReceiveSignalingPacket(), ns3::SatUtMac::ReceiveSignalingPacket(), ns3::SatGwMac::ReceiveSignalingPacket(), and ns3::SatMac::SendPacket().
GetSerializedSize()
uint32_t ns3::SatControlMsgTag::GetSerializedSize (void) const virtual
Get serialized size of methods.
Returns
Serialized size in bytes
Definition at line 87 of file satellite-control-message.cc.
References m_msgId, and m_msgType.
GetTypeId()
TypeId ns3::SatControlMsgTag::GetTypeId (void) static
methods derived from base classes
Definition at line 57 of file satellite-control-message.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatControlMsgTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of methods.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 111 of file satellite-control-message.cc.
References m_msgId, and m_msgType.
Serialize()
void ns3::SatControlMsgTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of methods.
Parameters
i Buffer in which the information is serialized
Definition at line 95 of file satellite-control-message.cc.
References m_msgId, and m_msgType.
SetMsgId()
void ns3::SatControlMsgTag::SetMsgId (uint32_t msgId) virtual
Set message type specific identifier.
Parameters
msgId Message type specific identifier. May be ignored by some message types.
Definition at line 118 of file satellite-control-message.cc.
References m_msgId.
Referenced by ns3::SatNetDevice::SendControlMsg(), ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder(), and ns3::SatMac::SendPacket().
SetMsgType()
void ns3::SatControlMsgTag::SetMsgType (SatControlMsgType_t type)
Set type of the control message.
In construction phase initialized to value SAT_UNKNOWN_CTRL_MSG.
Parameters
type The type of the control message
Definition at line 73 of file satellite-control-message.cc.
References m_msgType.
Referenced by ns3::SatNetDevice::SendControlMsg(), and ns3::SatOrbiterNetDeviceDvb::SendControlMsgToFeeder().
Member Data Documentation
m_msgId
uint32_t ns3::SatControlMsgTag::m_msgId private
Definition at line 147 of file satellite-control-message.h.
Referenced by Deserialize(), GetMsgId(), GetSerializedSize(), Print(), Serialize(), and SetMsgId().
m_msgType
SatControlMsgType_t ns3::SatControlMsgTag::m_msgType private
Definition at line 146 of file satellite-control-message.h.
Referenced by Deserialize(), GetMsgType(), GetSerializedSize(), Print(), Serialize(), and SetMsgType().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-control-message.h
/builds/sns3/satellite/satellite/model/satellite-control-message.cc