SNS3
SatRegenerationTest6 Class Reference
'Regeneration, test 6' test case implementation.
Public Member Functions
SatRegenerationTest6 ()
virtual ~SatRegenerationTest6 ()
Private Member Functions
virtual void DoRun (void)
bool HasSinkInstalled (Ptr< Node > node, uint16_t port)
void OrbiterDevGwRxTraceCb (Ptr< const Packet > packet, const Address &)
void OrbiterDevGwTxTraceCb (Ptr< const Packet > packet)
void OrbiterDevUtRxTraceCb (Ptr< const Packet > packet, const Address &)
void OrbiterDevUtTxTraceCb (Ptr< const Packet > packet)
Private Attributes
Ptr< SatHelper > m_helper
uint32_t m_totalReceivedGw
uint32_t m_totalReceivedUt
uint32_t m_totalSentGw
uint32_t m_totalSentUt
Detailed Description
'Regeneration, test 6' test case implementation.
This case tests network regeneration on satellite. It is based on a LARGER scenario.
Expected result: Same number of bytes sent and received on FWD Same number of bytes sent and received on RTN
Definition at line 1334 of file satellite-regeneration-test.cc.
Constructor & Destructor Documentation
SatRegenerationTest6()
SatRegenerationTest6::SatRegenerationTest6 ()
Definition at line 1400 of file satellite-regeneration-test.cc.
References m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, and m_totalSentUt.
~SatRegenerationTest6()
SatRegenerationTest6::~SatRegenerationTest6 () virtual
Definition at line 1412 of file satellite-regeneration-test.cc.
Member Function Documentation
DoRun()
void SatRegenerationTest6::DoRun (void) private virtual
Set regeneration mode
Set simulation output details
Definition at line 1420 of file satellite-regeneration-test.cc.
References m_helper, m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, m_totalSentUt, OrbiterDevGwRxTraceCb(), OrbiterDevGwTxTraceCb(), OrbiterDevUtRxTraceCb(), and OrbiterDevUtTxTraceCb().
HasSinkInstalled()
bool SatRegenerationTest6::HasSinkInstalled (Ptr< Node > node, uint16_t port) private
Definition at line 1381 of file satellite-regeneration-test.cc.
OrbiterDevGwRxTraceCb()
void SatRegenerationTest6::OrbiterDevGwRxTraceCb (Ptr< const Packet > packet, const Address &) private
Definition at line 1369 of file satellite-regeneration-test.cc.
References m_totalReceivedGw.
Referenced by DoRun().
OrbiterDevGwTxTraceCb()
void SatRegenerationTest6::OrbiterDevGwTxTraceCb (Ptr< const Packet > packet) private
Definition at line 1357 of file satellite-regeneration-test.cc.
References m_totalSentGw.
Referenced by DoRun().
OrbiterDevUtRxTraceCb()
void SatRegenerationTest6::OrbiterDevUtRxTraceCb (Ptr< const Packet > packet, const Address & address) private
Definition at line 1375 of file satellite-regeneration-test.cc.
References m_totalReceivedUt.
Referenced by DoRun().
OrbiterDevUtTxTraceCb()
void SatRegenerationTest6::OrbiterDevUtTxTraceCb (Ptr< const Packet > packet) private
Definition at line 1363 of file satellite-regeneration-test.cc.
References m_totalSentUt.
Referenced by DoRun().
Member Data Documentation
m_helper
Ptr<SatHelper> SatRegenerationTest6::m_helper private
Definition at line 1348 of file satellite-regeneration-test.cc.
Referenced by DoRun().
m_totalReceivedGw
uint32_t SatRegenerationTest6::m_totalReceivedGw private
Definition at line 1352 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and OrbiterDevGwRxTraceCb().
m_totalReceivedUt
uint32_t SatRegenerationTest6::m_totalReceivedUt private
Definition at line 1353 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and OrbiterDevUtRxTraceCb().
m_totalSentGw
uint32_t SatRegenerationTest6::m_totalSentGw private
Definition at line 1350 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and OrbiterDevGwTxTraceCb().
m_totalSentUt
uint32_t SatRegenerationTest6::m_totalSentUt private
Definition at line 1351 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and OrbiterDevUtTxTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-regeneration-test.cc